import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import test from 'node:test';
const env={STRIPE_API_KEY:'sk_test_fixture',STRIPE_CARD_ID:'ic_fixture',STRIPE_CARDHOLDER_ID:'ich_fixture',BROWSERBASE_API_KEY:'fixture',STRIPE_TEST_AUTHORIZATION_KEY:'fixture-order-1'};
function fixture({card={},holder={},receipt={},authorization={},failure,realBrowser}={}){
 const calls={allocated:0,released:0,closed:0,authorization:[],logs:[],cardRequests:[]};
 const validHolder={id:'ich_fixture',livemode:false,status:'active',requirements:{disabled_reason:null,past_due:[]},...holder};
 class Stripe {constructor(){this.issuing={cards:{retrieve:async(...args)=>{calls.cardRequests.push(args);return{id:'ic_fixture',cardholder:'ich_fixture',livemode:false,status:'active',...card};}},cardholders:{retrieve:async()=>validHolder}};this.testHelpers={issuing:{authorizations:{create:async(...args)=>{calls.authorization.push(args);if(failure==='authorization')throw Error('authorization failed');return{id:'iauth_fixture',card:'ic_fixture',cardholder:'ich_fixture',livemode:false,approved:true,status:'pending',amount:1000,currency:'usd',...authorization};}}}};}}
 class Browserbase {constructor(){this.sessions={create:async(body)=>{assert.equal(body.api_timeout,300);calls.allocated++;return{id:'session-fixture',connectUrl:'wss://fixture.invalid'};},update:async(id,body)=>{calls.released++;assert.equal(id,'session-fixture');assert.equal(body.status,'REQUEST_RELEASE');if(failure==='release')throw Error('release failed');}};}}
 const page={setContent:async html=>{assert.ok(!html.includes('ic_fixture'));assert.ok(!html.includes('sk_test_'));},locator:selector=>({click:async()=>{},evaluate:async()=>({amount:'1000',currency:'usd',nonce:'fixture-nonce',text:'Test order confirmed',...receipt})})};
 const browser={contexts:()=>[{newPage:async()=>page}],close:async()=>{calls.closed++;if(failure==='close')throw Error('close failed');}};
 const chromium={connectOverCDP:async()=>{if(failure==='connect')throw Error('connect failed');return realBrowser || browser;}};
 const source=readFileSync(new URL('../node/4-make-payment.ts',import.meta.url),'utf8').replace(/^import .*;\s*$/gm,'').replace(/^export /gm,'').replace(/\nif \(process\.argv\[1\][\s\S]*$/,'');
 const context=vm.createContext({Stripe,Browserbase,chromium,randomUUID:()=> 'fixture-nonce',process:{env:{...env}},console:{log:(...x)=>calls.logs.push(x)}});vm.runInContext(stripTypeScriptTypes(source),context);return{context,calls};
}
test('owned confirmation leads to one matching idempotent test authorization',async()=>{const{context,calls}=fixture();await context.run();assert.equal(calls.authorization.length,1);const[body,options]=calls.authorization[0];assert.equal(body.amount,1000);assert.equal(body.currency,'usd');assert.equal(options.idempotencyKey,env.STRIPE_TEST_AUTHORIZATION_KEY);assert.equal(calls.cardRequests[0].length,1);assert.equal(calls.released,1);assert.equal(calls.closed,1);assert.equal(calls.logs.length,1);});
for(const field of Object.keys(env))test(`missing ${field} prevents allocation`,async()=>{const{context,calls}=fixture();delete context.process.env[field];await assert.rejects(context.run());assert.equal(calls.allocated,0);assert.equal(calls.authorization.length,0);});
for(const card of [{status:'inactive'},{livemode:true},{id:'ic_other'}])test(`invalid card prevents browser allocation ${JSON.stringify(card)}`,async()=>{const{context,calls}=fixture({card});await assert.rejects(context.run());assert.equal(calls.allocated,0);});
for(const receipt of [{amount:'1001'},{nonce:'stale'},{text:'pending'}])test(`receipt mismatch prevents authorization ${JSON.stringify(receipt)}`,async()=>{const{context,calls}=fixture({receipt});await assert.rejects(context.run());assert.equal(calls.authorization.length,0);assert.equal(calls.released,1);});
for(const authorization of [{approved:false},{status:'closed'},{livemode:true},{amount:999},{currency:'eur'},{card:'ic_other'},{cardholder:'ich_other'}])test(`bad authorization is not success ${JSON.stringify(authorization)}`,async()=>{const{context,calls}=fixture({authorization});await assert.rejects(context.run());assert.equal(calls.logs.length,0);assert.equal(calls.released,1);});
for(const failure of ['connect','close','release','authorization'])test(`cleanup/outcome after ${failure} failure`,async()=>{const{context,calls}=fixture({failure});await assert.rejects(context.run());assert.equal(calls.released,1);assert.equal(calls.closed,failure==='connect'?0:1);assert.equal(calls.logs.length,0);});
test('real local browser renders and confirms the owned fixture', {skip:!process.env.COOKBOOK_PLAYWRIGHT_MODULE},async()=>{const{chromium}=await import(process.env.COOKBOOK_PLAYWRIGHT_MODULE);const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{await browser.newContext();const{context,calls}=fixture({realBrowser:browser});await context.run();assert.equal(calls.authorization.length,1);assert.equal(calls.released,1);}finally{await browser.close();}});
