import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';
const raw=readFileSync(process.env.STREAM_SOURCE_PATH || new URL('../app/api/demo/stream/route.ts',import.meta.url),'utf8');
const source=stripTypeScriptTypes(raw.replace(/^import [\s\S]*?;\n/gm,'')).replaceAll('export ','');
async function fixture(options={}){let subscriber,beat,subscriptions=0,unsubscribed=0,timers=0,cleared=0;const abort=new AbortController();if(options.preaborted)abort.abort();const circular={};circular.self=circular;
 const scope=vm.createContext({URL,Response,ReadableStream,TextEncoder,getDemoSnapshot:()=>{if(options.snapshotError)throw Error('synthetic');return {status:'synthetic'};},subscribeToDemo:(_id,fn)=>{if(options.subscribeError)throw Error('synthetic');subscriptions++;subscriber=fn;if(options.abortSubscribe)abort.abort();if(options.badSubscribe)fn(circular);return ()=>{unsubscribed++;};},setInterval:fn=>{timers++;beat=fn;return 7;},clearInterval:()=>{cleared++;}});
 vm.runInContext(source+'\nglobalThis.get=GET;',scope);const response=await scope.get(new Request('https://synthetic.invalid/?'+(options.missing?'':'demoId=synthetic'),{signal:abort.signal}));
 return {response,abort,circular,send:v=>subscriber?.(v),ping:()=>beat?.(),counts:()=>({subscriptions,unsubscribed,timers,cleared})};}
test('body cancellation cleans timer/subscription and retained callbacks become no-ops',async()=>{const f=await fixture();await f.response.body.cancel();assert.deepEqual(f.counts(),{subscriptions:1,unsubscribed:1,timers:1,cleared:1});assert.doesNotThrow(()=>{f.ping();f.send({late:true});f.abort.abort();});assert.equal(f.counts().unsubscribed,1);});
test('abort closes stream and cleans exactly once',async()=>{const f=await fixture();const reader=f.response.body.getReader();await reader.read();f.abort.abort();assert.equal((await reader.read()).done,true);await reader.cancel();assert.equal(f.counts().unsubscribed,1);assert.equal(f.counts().cleared,1);});
test('already aborted request allocates no subscriber or heartbeat',async()=>{const f=await fixture({preaborted:true});assert.equal((await f.response.body.getReader().read()).done,true);assert.deepEqual(f.counts(),{subscriptions:0,unsubscribed:0,timers:0,cleared:0});});
for(const key of ['abortSubscribe','badSubscribe'])test('synchronous subscription teardown: '+key,async()=>{const f=await fixture({[key]:true});assert.equal(f.counts().unsubscribed,1);assert.equal(f.counts().timers,0);if(key==='badSubscribe')await assert.rejects(f.response.text());else await f.response.text();});
for(const key of ['snapshotError','subscribeError'])test('initialization failure releases resources: '+key,async()=>{const f=await fixture({[key]:true});await assert.rejects(f.response.text());assert.equal(f.counts().timers,0);f.abort.abort();});
test('serialization failure errors stream and releases active resources',async()=>{const f=await fixture();assert.doesNotThrow(()=>f.send(f.circular));await assert.rejects(f.response.text());assert.equal(f.counts().unsubscribed,1);assert.equal(f.counts().cleared,1);assert.doesNotThrow(f.ping);});
test('SSE snapshot/update/ping frames still reach an active consumer',async()=>{const f=await fixture();const reader=f.response.body.getReader();const decoder=new TextDecoder();assert.match(decoder.decode((await reader.read()).value),/event: snapshot\ndata: {"status":"synthetic"}\n\n/);f.send({version:2});assert.match(decoder.decode((await reader.read()).value),/"version":2/);f.ping();assert.equal(decoder.decode((await reader.read()).value),'event: ping\ndata: {}\n\n');await reader.cancel();});
test('missing demo ID remains a 400 response without resources',async()=>{const f=await fixture({missing:true});assert.equal(f.response.status,400);assert.equal(f.counts().subscriptions,0);});
