import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';
const src=readFileSync(process.env.VOICE_SOURCE_PATH || new URL('../app/demo-client.tsx',import.meta.url),'utf8');
const end=src.indexOf('  const startControllerRun');const segment=src.slice(src.lastIndexOf('  useEffect(',end),end);
const effect=segment.slice(segment.indexOf('() => {'),segment.lastIndexOf('}, [')+1);
const callback=(name,next)=>src.slice(src.indexOf('    '+name+': ')+name.length+6,src.indexOf('    '+next+': ')).trim().replace(/,$/,'');
const builder=src.slice(src.indexOf('function buildVoiceContext('),src.indexOf('function buildToolVoiceGuidance('));
const code=stripTypeScriptTypes(builder+';globalThis.effect='+effect+';globalThis.connect='+callback('onConnect','onDisconnect')+';globalThis.disconnect='+callback('onDisconnect','onStatusChange')+';globalThis.build=buildVoiceContext;');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(sender=()=>{}){let timer,clears=0;const ctx=vm.createContext({session:{status:'blocked',lastControlMessage:'Synthetic clarification',activeRunId:'synthetic'},lastVoiceContextRef:{current:null},voiceConnectionRef:{current:{epoch:1,connected:true}},voiceConnected:true,sendContextualUpdate:sender,appendTranscriptLine(){},setVoiceConnectionEpoch(){},setTimeout:fn=>{timer=fn;return 1;},clearTimeout:()=>{timer=undefined;clears++;}});vm.runInContext(code,ctx);const context=ctx.build(ctx.session);ctx.voiceContextKey=context.key;ctx.voiceContextMessage=context.message;return {ctx,retry:()=>timer?.(),hasTimer:()=>Boolean(timer),clears:()=>clears};}
for(const session of [{status:'incomplete',lastSummary:'Synthetic step limit'},{status:'blocked',lastControlMessage:'Synthetic clarification'},{status:'error',error:'Synthetic error'},{lastControlOutcome:'completed',lastSummary:'Synthetic summary'}])test('unchanged state reaches a new connection: '+JSON.stringify(session),async()=>{let first=0,second=0;const f=fixture(()=>first++);f.ctx.session={...session,activeRunId:'synthetic'};const context=f.ctx.build(f.ctx.session);f.ctx.voiceContextKey=context.key;f.ctx.voiceContextMessage=context.message;let cleanup=f.ctx.effect();await flush();cleanup?.();f.ctx.disconnect({});f.ctx.voiceConnected=false;f.ctx.effect();f.ctx.connect({conversationId:'synthetic-new'});f.ctx.voiceConnected=true;f.ctx.sendContextualUpdate=()=>{second++;};cleanup=f.ctx.effect();await flush();assert.equal(first,1);assert.equal(second,1);cleanup?.();});
test('successful local delivery deduplicates within a connection',async()=>{let calls=0;const f=fixture(()=>{calls++;});const cleanup=f.ctx.effect();await flush();f.ctx.effect();assert.equal(calls,1);cleanup?.();});
for(const mode of ['throw','reject','false'])test('failed send retries without marking delivery: '+mode,async()=>{let calls=0;const f=fixture(()=>{calls++;if(calls===1){if(mode==='throw')throw Error('synthetic');if(mode==='reject')return Promise.reject(Error('synthetic'));return false;}});const cleanup=f.ctx.effect();await flush();assert.equal(f.ctx.lastVoiceContextRef.current,null);assert.equal(f.hasTimer(),true);f.retry();await flush();assert.equal(calls,2);assert.equal(f.ctx.lastVoiceContextRef.current,f.ctx.voiceContextKey);cleanup();});
test('disconnect invalidates a pending send before React effect cleanup',async()=>{let resolve;const f=fixture(()=>new Promise(r=>resolve=r));const cleanup=f.ctx.effect();f.ctx.disconnect({});resolve();await flush();assert.equal(f.ctx.lastVoiceContextRef.current,null);cleanup();});
test('effect cleanup clears retries and prevents late sends',async()=>{let calls=0;const f=fixture(()=>{calls++;throw Error('synthetic');});const cleanup=f.ctx.effect();await flush();cleanup();f.retry();assert.equal(calls,1);assert.equal(f.clears(),1);});
test('new onConnect resends even when status remains connected',async()=>{let calls=0;const f=fixture(()=>{calls++;});const old=f.ctx.effect();await flush();f.ctx.connect({conversationId:'replacement'});old?.();const cleanup=f.ctx.effect();await flush();assert.equal(calls,2);cleanup?.();});
test('late rejection from replaced connection does not schedule a retry',async()=>{let reject;const f=fixture(()=>new Promise((_resolve,r)=>reject=r));const cleanup=f.ctx.effect();f.ctx.disconnect({});reject(Error('synthetic late rejection'));await flush();assert.equal(f.hasTimer(),false);cleanup();});
test('irrelevant controller state sends no context',()=>{let calls=0;const f=fixture(()=>{calls++;});f.ctx.voiceContextKey=undefined;f.ctx.voiceContextMessage=undefined;f.ctx.effect();assert.equal(calls,0);});
