import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {fileURLToPath,pathToFileURL} from 'node:url';
import vm from 'node:vm';
import test from 'node:test';
import {createJournal,fingerprint} from '../journal.mjs';
function fixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'cookbook-r173-test-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const entry=path.join(root,'fixture.workflow.mjs');fs.writeFileSync(entry,'synthetic workflow v1');return {root,entry,directory:path.join(root,'journals')};}
test('canonical keys sort properties and distinguish schema/task values',()=>{assert.equal(fingerprint({a:1,b:2}),fingerprint({b:2,a:1}));assert.notEqual(fingerprint({task:'one'}),fingerprint({task:'two'}));for(const value of [undefined,Infinity,()=>{},new Date(),[undefined]])assert.throws(()=>fingerprint(value));});
test('journal survives restart and returned values are defensive copies',t=>{const f=fixture(t);const j=createJournal({...f,identity:{workflow:'one'}});const out={nested:{value:1}};j.set('key',out);out.nested.value=2;const read=j.get('key');read.nested.value=3;assert.equal(j.get('key').nested.value,1);assert.equal(createJournal({...f,identity:{workflow:'one'}}).get('key').nested.value,1);assert.equal(fs.statSync(j.filePath).mode&0o777,0o600);});
test('different workflows isolate files and ignore legacy journal',t=>{const f=fixture(t);fs.mkdirSync(f.directory);fs.writeFileSync(path.join(f.directory,'.journal.json'),'not even JSON');const a=createJournal({...f,identity:'a'});a.set('key','one');const b=createJournal({...f,identity:'b'});assert.equal(b.has('key'),false);assert.notEqual(a.filePath,b.filePath);});
test('fresh run discards previous entries once and retains its new entries',t=>{const f=fixture(t);createJournal({...f,identity:'one'}).set('old',1);const j=createJournal({...f,identity:'one',fresh:true});assert.equal(j.has('old'),false);j.set('new',2);j.set('next',3);const loaded=createJournal({...f,identity:'one'});assert.equal(loaded.has('old'),false);assert.equal(loaded.get('new'),2);assert.equal(loaded.get('next'),3);});
test('independent instances merge writes under a lock',t=>{const f=fixture(t);const a=createJournal({...f,identity:'one'}),b=createJournal({...f,identity:'one'});a.set('a',1);b.set('b',2);const loaded=createJournal({...f,identity:'one'});assert.equal(loaded.get('a'),1);assert.equal(loaded.get('b'),2);});
test('malformed and wrong-identity files fail closed',t=>{const f=fixture(t);const j=createJournal({...f,identity:'one'});for(const body of ['not JSON',JSON.stringify({version:2,identityHash:'wrong',entries:{}})]){fs.writeFileSync(j.filePath,body);assert.throws(()=>createJournal({...f,identity:'one'}));assert.throws(()=>createJournal({...f,identity:'one',fresh:true}));assert.equal(fs.readFileSync(j.filePath,'utf8'),body);}});
test('symlink file and directory are rejected',t=>{const f=fixture(t);const j=createJournal({...f,identity:'one'});const target=path.join(f.root,'target');fs.writeFileSync(target,'preserve');fs.symlinkSync(target,j.filePath);assert.throws(()=>j.set('a',1));assert.equal(fs.readFileSync(target,'utf8'),'preserve');const link=path.join(f.root,'link');fs.symlinkSync(f.directory,link);assert.throws(()=>createJournal({directory:link,identity:'one'}));});
test('existing lock prevents replacement and remains untouched',t=>{const f=fixture(t);const j=createJournal({...f,identity:'one'});j.set('old',1);const before=fs.readFileSync(j.filePath);fs.writeFileSync(j.filePath+'.lock','other writer');assert.throws(()=>j.set('new',2));assert.deepEqual(fs.readFileSync(j.filePath),before);assert.equal(fs.readFileSync(j.filePath+'.lock','utf8'),'other writer');});
function harness(f,options={}){
 const sourcePath=fileURLToPath(new URL('../harness.mjs',import.meta.url));const source=fs.readFileSync(process.env.COOKBOOK_R173_BASELINE||sourcePath,'utf8').replace(/^import .*;\s*$/gm,'').replace(/import\.meta\.url/g,JSON.stringify(pathToFileURL(process.env.COOKBOOK_R173_BASELINE?f.entry:sourcePath).href)).replace(/^export /gm,'');
 const journalSource=fs.readFileSync(new URL('../journal.mjs',import.meta.url),'utf8').replace(/^import .*;\s*$/gm,'').replace(/^export /gm,'');
 const localFs={...fs};if(options.renameFailure)localFs.renameSync=()=>{throw Error('synthetic rename failure');};
 const context=vm.createContext({fs:localFs,path,createHash,randomUUID,readFileSync:fs.readFileSync,writeFileSync:fs.writeFileSync,existsSync:fs.existsSync,realpathSync:fs.realpathSync,dirname:path.dirname,resolve:path.resolve,fileURLToPath,process:{env:{ANTHROPIC_API_KEY:'synthetic-key',BAC_JOURNAL_DIR:f.directory,...options.env},argv:['node',options.entry||f.entry,...(options.fresh?['--fresh']:[])],cwd:()=>f.root},console:{log(){}},URL,setTimeout,clearTimeout});
 vm.runInContext(journalSource,context);vm.runInContext(source,context);
 vm.runInContext('globalThis.calls=[]; leafWithSchema=async(task,opts)=>{calls.push({task,opts});return {answer:task}}',context);
 return {context,async agent(task='task one',opts={}){context.input=JSON.stringify({task,opts});return JSON.parse(JSON.stringify(await vm.runInContext('agent(JSON.parse(input).task,JSON.parse(input).opts)',context)));},get calls(){return context.calls;}};
}
test('actual harness reuses only identical leaf identity across reruns',async t=>{const f=fixture(t);const a=harness(f);assert.equal((await a.agent()).answer,'task one');const b=harness(f);assert.equal((await b.agent()).answer,'task one');assert.equal(b.calls.length,0);const c=harness(f);assert.equal((await c.agent('task two')).answer,'task two');assert.equal(c.calls.length,1);});
test('schema, source, credential and execution context changes do not reuse',async t=>{const f=fixture(t);await harness(f).agent('task',{resultSchema:{type:'object'}});for(const options of [{env:{BAC_MODEL:'synthetic-model'}},{env:{ANTHROPIC_API_KEY:'another-synthetic-key'}},{env:{BAC_CONTEXT_VERSION:'2'}}]){const h=harness(f,options);await h.agent('task',{resultSchema:{type:'object'}});assert.equal(h.calls.length,1);}const changed=harness(f);await changed.agent('task',{resultSchema:{type:'string'}});assert.equal(changed.calls.length,1);fs.writeFileSync(f.entry,'synthetic workflow v2');const newer=harness(f);await newer.agent('task',{resultSchema:{type:'object'}});assert.equal(newer.calls.length,1);});
test('fresh and cache false force execution',async t=>{const f=fixture(t);await harness(f).agent();const fresh=harness(f,{fresh:true});await fresh.agent();assert.equal(fresh.calls.length,1);const uncached=harness(f);await uncached.agent('task one',{cache:false});assert.equal(uncached.calls.length,1);});
test('explicit workflow identity requires a version',async t=>{const f=fixture(t);await assert.rejects(harness(f,{env:{BAC_WORKFLOW_ID:'synthetic'}}).agent(),/BAC_WORKFLOW_VERSION/);});
test('failed atomic replacement preserves committed data and cleans temporary files',async t=>{const f=fixture(t);await harness(f).agent();const before=fs.readdirSync(f.directory).map(name=>[name,fs.readFileSync(path.join(f.directory,name),'utf8')]);await assert.rejects(harness(f,{renameFailure:true}).agent('task two'),/synthetic rename failure/);assert.deepEqual(fs.readdirSync(f.directory).map(name=>[name,fs.readFileSync(path.join(f.directory,name),'utf8')]),before);});

test('different entrypoints and schemas with reordered properties have correct scope',async t=>{const f=fixture(t);await harness(f).agent('task',{resultSchema:{type:'object',properties:{a:{type:'number'},b:{type:'string'}}}});const same=harness(f);await same.agent('task',{resultSchema:{properties:{b:{type:'string'},a:{type:'number'}},type:'object'}});assert.equal(same.calls.length,0);const entry=path.join(f.root,'another.workflow.mjs');fs.copyFileSync(f.entry,entry);const other=harness(f,{entry});await other.agent('task',{resultSchema:{type:'object',properties:{a:{type:'number'},b:{type:'string'}}}});assert.equal(other.calls.length,1);});
test('mutable schema is snapshotted before a queued leaf runs',async t=>{const f=fixture(t);const h=harness(f);await vm.runInContext('globalThis.schema={type:"object"};globalThis.pending=agent("task",{resultSchema:schema});schema.type="string";pending',h.context);assert.equal(h.calls[0].opts.resultSchema.type,'object');});
test('schema failure sentinel is never persisted as a completed leaf',async t=>{const f=fixture(t);const h=harness(f);vm.runInContext('leafWithSchema=async()=>({_invalid:"synthetic schema failure"})',h.context);await h.agent();const next=harness(f);await next.agent();assert.equal(next.calls.length,1);});
