import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
const controls='function compute('+fs.readFileSync(process.env.COOKBOOK_R174_HARNESS_BASELINE || new URL('../harness.mjs',import.meta.url),'utf8').split('export function compute(')[1].replace(/^export /gm,'');
const workflow=fs.readFileSync(process.env.COOKBOOK_R174_BASELINE || new URL('../examples/price-compare.workflow.mjs',import.meta.url),'utf8').replace(/import\s*\{[\s\S]*?\}\s*from\s*"\.\.\/harness\.mjs";/,'');
const listing=(merchant,price=10,shipping=2)=>({name:'Synthetic product',price_usd:price,shipping_cost_usd:shipping,url:`https://fixture.invalid/${merchant}`,currency:'USD',in_stock:true,ships_to_zip:'yes'});
async function run(options={}){
 const data=options.data||{One:{blocked:false,items:[listing('One')]},Two:{blocked:false,items:[listing('Two',13,1)]}};
 const logs=[],calls=[];
 const context=vm.createContext({process:{env:{QUERY:'Synthetic product',ZIP:'00123',MERCHANTS:'One,Two',...options.env}},URL,console:{log:m=>logs.push(String(m))},log:m=>logs.push(String(m)),phase(){},async agent(task,opts){calls.push({task,opts});if(opts.label==='verify-winner'){if(options.verificationError)throw Error('synthetic verification failure');const url=task.match(/Open (\S+) in/)?.[1];const item=Object.values(data).flatMap(r=>r?.items||[]).find(i=>i.url===url)||{};return {destination_zip:'00123',url,currency:item.currency,in_stock:item.in_stock,ships_to_zip:item.ships_to_zip,price_usd:item.price_usd,shipping_usd:item.shipping_cost_usd,...options.verification};}if(data[opts.label] instanceof Error)throw data[opts.label];return data[opts.label];}});
 vm.runInContext(controls,context);
 const result=await vm.runInContext(`(async()=>{${workflow}\nreturn {ranked,cheapest};})()`,context);
 return {result:JSON.parse(JSON.stringify(result)),logs,calls};
}
const recommends=result=>result.logs.some(line=>line.includes('Verified lowest') || line.includes('Cheapest delivered to'));
test('only literal true verifies; false unknown and errors remain explicit',async()=>{const context=vm.createContext({log(){},console:{log(){}}});vm.runInContext(controls,context);const results=await vm.runInContext('verify([{id:"yes",run:async()=>true},{id:"no",run:async()=>false},{id:"missing",run:async()=>undefined},{id:"truthy",run:async()=>"yes"},{id:"error",run:async()=>{throw Error("synthetic")}}])',context);assert.deepEqual(Array.from(results,x=>[x.pass,x.status]),[[true,'passed'],[false,'failed'],[false,'unknown'],[false,'unknown'],[false,'error']]);});
test('invalid or duplicate check IDs cannot pass',async()=>{const context=vm.createContext({log(){},console:{log(){}}});vm.runInContext(controls,context);const results=await vm.runInContext('verify([{id:"same",run:async()=>true},{id:"same",run:async()=>true},{run:async()=>true}])',context);assert.ok(results.every(x=>x.pass===false&&x.status==='error'));});
test('matching fresh quote permits a scoped recommendation',async()=>{const r=await run();assert.equal(recommends(r),true);assert.equal(r.result.cheapest.delivered_usd,12);const fresh=r.calls.find(x=>x.opts.label==='verify-winner');assert.equal(fresh.opts.cache,false);assert.match(fresh.task,/00123/);assert.ok(r.logs.some(x=>x.includes('exclude tax')));});
for(const [name,verification] of Object.entries({shippingChanged:{shipping_usd:3},shippingUnknown:{shipping_usd:null},priceChanged:{price_usd:10.01},wrongCurrency:{currency:'EUR'},outOfStock:{in_stock:false},noShipping:{ships_to_zip:'no'},unknownShipping:{ships_to_zip:'unknown'},wrongUrl:{url:'https://fixture.invalid/other'},wrongZip:{destination_zip:'123'},fractionalCent:{price_usd:10.001},stringPrice:{price_usd:'10'},schemaFailure:{_invalid:'synthetic',price_usd:undefined}})) test(`fresh ${name} blocks recommendation`,async()=>{const r=await run({verification});assert.equal(recommends(r),false);assert.ok(r.logs.some(x=>x.includes('Provisional comparison only')));});
test('throwing verification blocks recommendation and retains error status',async()=>{const r=await run({verificationError:true});assert.equal(recommends(r),false);assert.ok(r.logs.some(x=>x.includes('"status": "error"')));});
test('unknown shipping is never silently zero or ranked',async()=>{const r=await run({data:{One:{blocked:false,items:[listing('One',1,null)]},Two:{blocked:false,items:[listing('Two',13,1)]}}});assert.equal(r.result.ranked.length,1);assert.equal(r.result.ranked[0].merchant,'Two');assert.equal(recommends(r),false);assert.ok(r.logs.some(x=>x.includes('"delivered_usd": null')));});
test('blocked merchant leaves comparison provisional even when candidate passes',async()=>{const r=await run({data:{One:{blocked:false,items:[listing('One')]},Two:{blocked:true,items:[]}}});assert.equal(recommends(r),false);assert.ok(r.logs.some(x=>x.includes('Incomplete merchants: Two')));});
test('invalid merchant result cannot disappear from coverage',async()=>{const r=await run({data:{One:{blocked:false,items:[listing('One')]},Two:{_invalid:'synthetic'}}});assert.equal(recommends(r),false);assert.ok(r.logs.some(x=>x.includes('Incomplete merchants: Two')));});
test('unavailable and non-USD listings do not enter a USD ranking',async()=>{const r=await run({data:{One:{blocked:false,items:[{...listing('One'),in_stock:false}]},Two:{blocked:false,items:[{...listing('Two'),currency:'EUR'}]}}});assert.equal(r.result.ranked.length,0);assert.equal(recommends(r),false);assert.equal(r.calls.filter(x=>x.opts.label==='verify-winner').length,0);});
test('zero item and shipping amounts can be verified without division by zero',async()=>{const r=await run({data:{One:{blocked:false,items:[listing('One',0,0)]},Two:{blocked:false,items:[]}}});assert.equal(recommends(r),true);assert.equal(r.result.cheapest.delivered_usd,0);});
test('empty quote set never implies verified winner',async()=>{const r=await run({data:{One:{blocked:false,items:[]},Two:{blocked:false,items:[]}}});assert.equal(recommends(r),false);assert.ok(r.logs.some(x=>x.includes('no fully priced')));});
test('invalid destination fails before agent calls',async()=>{await assert.rejects(run({env:{ZIP:'not-a-zip'}}),/US ZIP code/);});
