import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire,stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';
const require=createRequire(import.meta.url),{z}=require(process.env.ZOD_MODULE_PATH || 'zod');const raw=readFileSync(process.env.PERF_SOURCE_PATH || new URL('../src/perf-vitals-agent.ts',import.meta.url),'utf8');const source=raw.slice(raw.indexOf('const startPerfMeasurement'),raw.indexOf('const getNavigationTiming'));
function fixture(unsupported=[]){let now=1000;const observers=[];const buffered={ 'largest-contentful-paint':[{startTime:200,element:{tagName:'IMG'}}], 'layout-shift':[{startTime:100,value:.3,hadRecentInput:false}],longtask:[{startTime:100,duration:90}] };
 class Observer{constructor(cb){this.cb=cb;this.pending=[];this.disconnected=false;observers.push(this);}observe({type}){this.type=type;if(unsupported.includes(type))throw Error('unsupported');this.cb({getEntries:()=>buffered[type]??[]});}takeRecords(){const result=this.pending;this.pending=[];return result;}disconnect(){this.disconnected=true;}}
 const window={location:{href:'https://synthetic.invalid/'}};const scope=vm.createContext({z,tool:value=>value,window,performance:{now:()=>now,getEntriesByType:type=>type==='paint'?[{name:'first-contentful-paint',startTime:50}]:[{responseStart:100,requestStart:50,loadEventEnd:200}]},PerformanceObserver:Observer,allMetrics:[],console:{log(){}},__stagehandPage:{evaluate:async(fn,arg)=>fn(arg)}});vm.runInContext(stripTypeScriptTypes(source)+'\nglobalThis.start=startPerfMeasurement;globalThis.collect=collectPerfMetrics;',scope);
 return {start:label=>scope.start.execute({label}),collect:label=>scope.collect.execute({label}),setNow:value=>now=value,observers,window,records:scope.allMetrics,emit:(type,entries)=>observers.find(o=>o.type===type&&!o.disconnected).cb({getEntries:()=>entries})};}
test('old buffered LCP/CLS/long tasks and document FCP do not contaminate a new window',async()=>{const f=fixture();await f.start('synthetic');f.setNow(1200);const {metrics}=await f.collect('synthetic');assert.equal(metrics.lcp_ms,null);assert.equal(metrics.fcp_ms,null);assert.equal(metrics.cls,0);assert.equal(metrics.long_tasks_count,0);assert.equal(metrics.ttfb_ms,null);assert.equal(metrics.measurement_scope,'interaction_window');assert.equal(f.records[0].measurement_scope,'interaction_window');});
test('in-window entries use elapsed candidate time and pending records are flushed through end boundary',async()=>{const f=fixture();await f.start('synthetic');f.setNow(1400);f.emit('largest-contentful-paint',[{startTime:1100,element:{tagName:'IMG'}}]);f.emit('layout-shift',[{startTime:1200,value:.2,hadRecentInput:false},{startTime:1300,value:1,hadRecentInput:true}]);f.emit('longtask',[{startTime:1250,duration:60}]);f.observers.find(o=>o.type==='longtask').pending=[{startTime:1450,duration:200},{startTime:1600,duration:90}];f.setNow(1500);const {metrics}=await f.collect('synthetic');assert.equal(metrics.lcp_ms,100);assert.equal(metrics.cls,.2);assert.equal(metrics.long_tasks_count,2);assert.equal(metrics.long_task_total_ms,110);assert.equal(metrics.wall_clock_ms,500);assert.ok(f.observers.every(o=>o.disconnected));});
test('collection freezes data despite retained callbacks and later collection',async()=>{const f=fixture();await f.start('synthetic');f.setNow(1200);const first=await f.collect('synthetic');f.setNow(3000);f.observers[1].cb({getEntries:()=>[{startTime:1100,value:5}]});const second=await f.collect('synthetic');assert.deepEqual(second.metrics,first.metrics);});
test('restarting a label disconnects old observers and resets the window',async()=>{const f=fixture();await f.start('synthetic');const old=[...f.observers];f.setNow(2000);await f.start('synthetic');assert.ok(old.every(o=>o.disconnected));old[1].cb({getEntries:()=>[{startTime:2000,value:1}]});const result=await f.collect('synthetic');assert.equal(result.metrics.cls,0);});
test('unsupported observers remain unknown, not measured zero',async()=>{const f=fixture(['layout-shift','longtask']);await f.start('synthetic');const {metrics}=await f.collect('synthetic');assert.equal(metrics.cls,null);assert.equal(metrics.cls_shift_count,null);assert.equal(metrics.long_tasks_count,null);assert.equal(metrics.long_task_total_ms,null);});
test('missing measurement cannot report metrics after a navigation',async()=>{const f=fixture();assert.equal((await f.collect('missing')).success,false);});
