import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire,stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';import {join} from 'node:path';
const require=createRequire(import.meta.url),{z}=require(process.env.ZOD_MODULE_PATH || 'zod'),{parse}=require(process.env.CSV_PARSE_MODULE_PATH || 'csv-parse/sync');
const raw=readFileSync(process.env.WORKFLOW_SOURCE_PATH || new URL('../workflow.ts',import.meta.url),'utf8');
const source=raw.slice(0,raw.indexOf('// Main execution')).replace(/^import [\s\S]*?;\n/gm,'');
const header='mcc,edited_description,combined_description,usda_description,irs_description,irs_reportable\r\n';
const csv=header+'1234,"Fixture, with comma",,USDA,IRS,Yes\r\n';
function fixture(options={}){let launched=0,extracted=0,requested=0;const scope=vm.createContext({z,parse,join,AbortSignal,process:{env:{OPENAI_API_KEY:'synthetic',GOOGLE_API_KEY:'synthetic',BROWSERBASE_API_KEY:'synthetic',},cwd:()=>'/synthetic'},readFileSync:()=>{if(options.readError)throw Error('missing reference');return options.csv??csv;},console:{log(){},error(){}},
 browserbase:{launch:async()=>{launched++;return {};}},StagehandCreateOptionsSchema:{parse:v=>v},
 Stagehand:{create:async()=>({browser:{context:{activePage:async()=>({goto:async()=>{}})},close:async()=>{}},extract:async()=>{extracted++;return {data:{dbaName:'Synthetic',businessAccountNumber:'fixture',naicsCode:'123456'}};},close:async()=>{}})},runBrowserTask:async()=>({completed:options.completed??true}),
 fetch:async()=>{requested++;if(options.network)throw Error('network');return {ok:options.ok??true,status:401,json:async()=>options.response??{choices:[{finish_reason:options.finish??'stop',message:{content:options.content??'[{"mcc":"1234","reasoning":"Synthetic match","editedDescription":"Invented description"}]'}}]}};},
 });vm.runInContext(stripTypeScriptTypes(source)+'\nglobalThis.api={loadMCCCodesFromCSV,determineMCCCodes,lookupBusinessCodes};',scope);return {scope,api:scope.api,launched:()=>launched,extracted:()=>extracted,requested:()=>requested};}
test('CSV keeps blank cells, quoted comma/newline/quotes and leading-zero codes',()=>{const f=fixture({csv:header+'0123,"One, two\nthree ""quoted""",,USDA,IRS,Yes\r\n'});const rows=f.api.loadMCCCodesFromCSV();assert.equal(rows.length,1);assert.equal(rows[0].mcc,'0123');assert.equal(rows[0].combinedDescription,'');assert.equal(rows[0].editedDescription,'One, two\nthree "quoted"');});
for(const value of ['',header,header+'1234,a,b\n',header+'1234,"unterminated',header+'xxxx,a,b,c,d,e',header+'1234,a,b,c,d,e\n1234,a,b,c,d,e',header+'1234,,,,,Yes'])test('invalid reference rejects: '+JSON.stringify(value),()=>assert.throws(()=>fixture({csv:value}).api.loadMCCCodesFromCSV()));
for(const options of [{ok:false},{network:true},{finish:'length'},{response:{choices:[]}},{content:'not json'},{content:'{}'},{content:'[{"mcc":"9999","reasoning":"unknown"}]'},{content:'[{"mcc":"1234","reasoning":""}]'},{content:'[{"mcc":"1234","reasoning":"x"},{"mcc":"1234","reasoning":"x"}]'}])test('classifier failure rejects: '+JSON.stringify(options),async()=>{const f=fixture(options);await assert.rejects(f.api.determineMCCCodes({},f.api.loadMCCCodesFromCSV()));});
test('valid empty selection means no match, and selected descriptions come from reference',async()=>{const empty=fixture({content:'[]'});assert.equal((await empty.api.determineMCCCodes({},empty.api.loadMCCCodesFromCSV())).length,0);const f=fixture();const selected=await f.api.determineMCCCodes({},f.api.loadMCCCodesFromCSV());assert.equal(selected[0].editedDescription,'Fixture, with comma');assert.equal(selected[0].reasoning,'Synthetic match');});
test('missing reference fails before browser launch',async()=>{const f=fixture({readError:true});assert.equal((await f.api.lookupBusinessCodes('Synthetic')).success,false);assert.equal(f.launched(),0);});
test('incomplete browser search stops before extraction/classifier',async()=>{const f=fixture({completed:false});assert.equal((await f.api.lookupBusinessCodes('Synthetic')).success,false);assert.equal(f.extracted(),0);assert.equal(f.requested(),0);});
test('classifier HTTP failure propagates unsuccessful lookup',async()=>{const f=fixture({ok:false});assert.equal((await f.api.lookupBusinessCodes('Synthetic')).success,false);});

for (const outcome of ['success','failure','throw']) test('actual CLI sets exit status: '+outcome, async()=>{
 const f=fixture();f.scope.process.argv=[];f.scope.lookupBusinessCodes=async()=>{if(outcome==='throw')throw Error('synthetic cleanup');return {success:outcome==='success'};};
 vm.runInContext(raw.slice(raw.indexOf('// Main execution')),f.scope);await new Promise(resolve=>setImmediate(resolve));assert.equal(f.scope.process.exitCode,outcome==='success'?0:1);
});
