import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire,stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';
const require=createRequire(import.meta.url),{z}=require(process.env.ZOD_MODULE_PATH || 'zod');const s=readFileSync(process.env.OFAC_SOURCE_PATH || new URL('../kyb-parallel.ts',import.meta.url),'utf8');const start=s.includes('function observeOfacResults')?s.indexOf('function observeOfacResults'):s.indexOf('async function ofacSdn');const end=s.indexOf('// ───',start);const scope=vm.createContext({z,MERCHANT:{legalName:'Synthetic'},setTimeout:fn=>{fn();return 1;}});vm.runInContext(stripTypeScriptTypes(s.slice(start,end))+'\nglobalThis.run=ofacSdn;',scope);
async function run(options={}){let actions=0,extracts=0,cleared=0;const page={goto:async()=>{},evaluate:async(_fn,input)=>{if(input.mode==='clear')cleared++;return {queryMatches:options.query??true,updated:options.updated??true,matchCount:options.visibleCount??0,armedAt:1};}};const result=await scope.run({browser:{context:{pages:async()=>[page]}},act:async()=>({data:{success:++actions!==(options.failedAction??-1)}}),extract:async()=>{extracts++;return {data:options.data??{matchCount:0,matches:[]}};}});return {result,actions,extracts,cleared};}
for(const failedAction of [1,2])test('failed action '+failedAction+' cannot pass',async()=>{const f=await run({failedAction});assert.equal(f.result.pass,null);assert.equal(f.extracts,0);assert.equal(f.cleared,1);});
for(const data of [{matchCount:0,matches:['Synthetic']},{matchCount:1,matches:[]},{matchCount:-1,matches:[]},{matchCount:0.5,matches:[]},{matchCount:1,matches:['']}])test('inconsistent extraction '+JSON.stringify(data),async()=>assert.equal((await run({data})).result.pass,null));
for(const option of [{query:false},{updated:false},{visibleCount:2}])test('missing or disagreeing browser evidence '+JSON.stringify(option),async()=>assert.equal((await run(option)).result.pass,null));
test('consistent observed zero is narrowly no_matches',async()=>{const f=await run();assert.equal(f.result.pass,true);assert.equal(f.result.status,'no_matches');assert.equal(f.cleared,1);});
test('consistent observed match is not a pass',async()=>{const f=await run({visibleCount:1,data:{matchCount:1,matches:['Synthetic']}});assert.equal(f.result.pass,false);assert.equal(f.result.status,'matches');});
for(const [pass,expected] of [[null,'UNKNOWN'],[false,'FAIL'],[true,'PASS']])test('aggregate preserves sanctions outcome '+expected,async()=>{const fragment=s.slice(s.indexOf('export async function runKyb'),s.indexOf('// CLI entry'));const c=vm.createContext({Date,MERCHANT:{legalName:'Synthetic'},delawareSoS(){},ofacSdn(){},usptoTrademark(){},runCheck:async options=>({pass:options.name.trim()==='OFAC'?pass:true})});vm.runInContext(stripTypeScriptTypes(fragment).replace('export ','')+'\nglobalThis.run=runKyb;',c);assert.equal((await c.run()).verdict,expected);});
test('actual UI renders unknown without asserting a match or clearance',()=>{const server=readFileSync(new URL('../server.ts',import.meta.url),'utf8');const fragment=server.slice(server.indexOf('    function esc('),server.indexOf('    function renderSummary('));const c=vm.createContext({});vm.runInContext(fragment+'\nglobalThis.render=renderDetails;globalThis.row=summaryRow;',c);const result={check:'ofac_sdn',pass:null,matchCount:null,matches:[],tookMs:1};assert.match(c.render(result),/Unknown/);assert.match(c.row('Synthetic',result),/Unknown/);assert.ok(!c.render(result).includes('Not on'));});
