// Generated by autobrowse export --target playwright from run-004, then hand-edited.
// Drives the LLC-1 wizard from the bizfile dashboard through Step 8 (Attachments),
// landing on Step 9 (Review and Signature). DOES NOT proceed past Step 9 — that's
// what the autobrowse handoff covers.
//
// Two modes:
//   - External session (hybrid): if BROWSERBASE_SESSION_ID is set, connect to that
//     existing session and leave it alive on exit (caller owns the lifecycle).
//   - Self-managed: if only BROWSERBASE_CONTEXT_ID is set, create a session, run,
//     release on exit (legacy/standalone path).
import { chromium, Browser } from "playwright";
import { z } from "zod";
import "dotenv/config";
import { execFileSync } from "node:child_process";

const OutputSchema = z.object({
  success: z.boolean(),
  llc_name: z.string(),
  stopped_at_step: z.string(),
  stopped_at_url: z.string(),
  fields_completed: z.array(z.string()),
  review_summary: z.object({
    principal_address: z.string(),
    mailing_address: z.string(),
    agent_name: z.string(),
    management_structure: z.string(),
    organizer_name: z.string(),
  }),
  payment_summary: z.object({
    cardholder_name: z.string(),
    card_last4: z.string(),
    billing_zip: z.string(),
  }),
  filing_fee_shown: z.string(),
  final_submit_button_label: z.string(),
  session_id: z.string().optional(),
});
type Output = z.infer<typeof OutputSchema>;

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v || v.trim() === "") {
    throw new Error(
      `Missing required env var: ${name}. Fill it in .env before running.`,
    );
  }
  return v.trim();
}

const PAYMENT_HANDOFF_ENABLED =
  process.env.BIZFILE_ALLOW_PAYMENT_HANDOFF === "true";
if (!PAYMENT_HANDOFF_ENABLED) {
  throw new Error(
    "BIZFILE_ALLOW_PAYMENT_HANDOFF must be set to true before this script signs the form, opens the payment screen, and fills card fields.",
  );
}

const LLC = {
  name: requireEnv("LLC_NAME"),
  principal: {
    street: requireEnv("LLC_PRINCIPAL_STREET"),
    city: requireEnv("LLC_PRINCIPAL_CITY"),
    state: requireEnv("LLC_PRINCIPAL_STATE"),
    zip: requireEnv("LLC_PRINCIPAL_ZIP"),
  },
  mailing: {
    street: requireEnv("LLC_MAILING_STREET"),
    city: requireEnv("LLC_MAILING_CITY"),
    state: requireEnv("LLC_MAILING_STATE"),
    zip: requireEnv("LLC_MAILING_ZIP"),
  },
  agent: {
    firstName: requireEnv("LLC_AGENT_FIRST_NAME"),
    lastName: requireEnv("LLC_AGENT_LAST_NAME"),
    street: requireEnv("LLC_AGENT_STREET"),
    city: requireEnv("LLC_AGENT_CITY"),
    state: requireEnv("LLC_AGENT_STATE"),
    zip: requireEnv("LLC_AGENT_ZIP"),
  },
  organizerName: requireEnv("LLC_ORGANIZER_NAME"),
};

// Cardholder name on .env is a single string ("First Last"); the bizfile payment
// form splits it into two fields. Split on the first whitespace; everything
// after the first token is the last name (handles e.g. "Mary Ann Smith").
const [cardholderFirst, ...cardholderRest] = requireEnv(
  "PAYMENT_CARDHOLDER_NAME",
).split(/\s+/);
const cardholderLast = cardholderRest.join(" ");
if (!cardholderLast) {
  throw new Error(
    "PAYMENT_CARDHOLDER_NAME must contain a first and last name separated by whitespace.",
  );
}

const PAYMENT = {
  cardholderFirst,
  cardholderLast,
  cardNumber: requireEnv("PAYMENT_CARD_NUMBER"),
  expMonth: requireEnv("PAYMENT_CARD_EXP_MONTH"),
  expYear: requireEnv("PAYMENT_CARD_EXP_YEAR"),
  cvv: requireEnv("PAYMENT_CARD_CVV"),
  billingAddress: requireEnv("PAYMENT_BILLING_ADDRESS"),
  billingCity: requireEnv("PAYMENT_BILLING_CITY"),
  billingState: requireEnv("PAYMENT_BILLING_STATE"),
  billingZip: requireEnv("PAYMENT_BILLING_ZIP"),
};

interface BbSession {
  wssUrl: string;
  sessionId: string;
  external: boolean;
}

function getBrowserbaseSession(): BbSession | null {
  const apiKey = process.env.BROWSERBASE_API_KEY;
  const externalSid = process.env.BROWSERBASE_SESSION_ID;

  if (externalSid) {
    if (!apiKey) {
      throw new Error(
        "BROWSERBASE_SESSION_ID is set but BROWSERBASE_API_KEY is missing.",
      );
    }
    const wssUrl = `wss://connect.browserbase.com?apiKey=${apiKey}&sessionId=${externalSid}`;
    return { wssUrl, sessionId: externalSid, external: true };
  }

  const ctx = process.env.BROWSERBASE_CONTEXT_ID;
  if (!ctx) return null;
  if (!apiKey || !process.env.BROWSERBASE_PROJECT_ID) {
    throw new Error(
      "BROWSERBASE_CONTEXT_ID is set but BROWSERBASE_API_KEY or BROWSERBASE_PROJECT_ID are missing.",
    );
  }
  const stdout = execFileSync(
    "bb",
    [
      "sessions",
      "create",
      "--context-id",
      ctx,
      "--persist",
      "--advanced-stealth",
      "--solve-captchas",
      "--keep-alive",
      "--timeout",
      "1800",
    ],
    { encoding: "utf-8" },
  );
  const session = JSON.parse(stdout);
  const wssUrl = `wss://connect.browserbase.com?apiKey=${apiKey}&sessionId=${session.id}`;
  return { wssUrl, sessionId: session.id, external: false };
}

function releaseBrowserbaseSession(bb: BbSession): void {
  try {
    execFileSync(
      "bb",
      ["sessions", "update", bb.sessionId, "--status", "REQUEST_RELEASE"],
      { stdio: "ignore" },
    );
  } catch {
    /* best-effort */
  }
}

async function main(): Promise<Output> {
  const bb = getBrowserbaseSession();
  const browser: Browser = bb
    ? await chromium.connectOverCDP(bb.wssUrl)
    : await chromium.launch({ headless: false });

  const context = bb ? browser.contexts()[0] : await browser.newContext();
  const page = context.pages()[0] ?? (await context.newPage());

  const fillField = async (
    labelPattern: RegExp | string,
    value: string,
  ): Promise<void> => {
    await page.getByLabel(labelPattern).first().click();
    await page.evaluate((v) => {
      const el = document.activeElement as HTMLInputElement | null;
      if (!el) throw new Error("No active element to fill");
      const setter = Object.getOwnPropertyDescriptor(
        HTMLInputElement.prototype,
        "value",
      )?.set;
      if (!setter) throw new Error("No value setter on HTMLInputElement");
      setter.call(el, v);
      el.dispatchEvent(new Event("input", { bubbles: true }));
      el.dispatchEvent(new Event("change", { bubbles: true }));
    }, value);
  };

  const nextStep = async (waitMs = 1500): Promise<void> => {
    await page.evaluate(
      `Array.from(document.querySelectorAll('button')).find(b => b.textContent.trim() === 'Next Step')?.click()`,
    );
    await page.waitForLoadState("load");
    await page.waitForTimeout(waitMs);
  };

  try {
    await page.goto("https://bizfileonline.sos.ca.gov/");
    await page.waitForLoadState("load");
    // Direct nav skips the SPA tour overlay that intercepts "Register a Business" link clicks.
    await page.goto("https://bizfileonline.sos.ca.gov/forms/business");
    await page.waitForLoadState("networkidle");
    await page.waitForLoadState("load");
    await page.waitForTimeout(3000);
    await page
      .locator(':text("Articles of Organization - CA LLC")')
      .first()
      .click();
    await page.waitForLoadState("load");
    await page.waitForTimeout(2000);
    await page.getByRole("button", { name: "FILE ONLINE" }).click();
    await page.waitForLoadState("load");
    await page.waitForTimeout(2000);

    // Step 1: T&C. force:true bypasses the styled-label overlay over the real input.
    await page.locator("input[type=checkbox]").check({ force: true });
    await page.evaluate(
      `Array.from(document.querySelectorAll('button')).find(b => b.textContent.trim() === 'Next Step')?.click()`,
    );
    await page.waitForTimeout(1500);

    // Step 2: Submitter (skipped)
    await nextStep(1000);
    // Step 3: Professional Services (skipped)
    await nextStep(1000);

    // Step 4: LLC Name
    await page
      .getByRole("radio", { name: /^No$/ })
      .first()
      .click({ force: true });
    await page.waitForTimeout(1000);
    console.error("[step4] filling LLC name:", LLC.name);
    await fillField(/^Limited Liability Company Name/i, LLC.name);
    await fillField(/Confirm Limited Liability Company Name/i, LLC.name);
    await nextStep(2000);

    // Step 5: Business Addresses
    console.error("[step5] filling principal address");
    await fillField(/Principal Address.*Address Line 1/i, LLC.principal.street);
    await fillField(/Principal Address.*City/i, LLC.principal.city);
    await page
      .getByLabel(/Principal Address.*State/i)
      .selectOption(LLC.principal.state);
    await fillField(/Principal Address.*ZIP/i, LLC.principal.zip);
    console.error("[step5] filling mailing address");
    await fillField(/Mailing Address.*Address Line 1/i, LLC.mailing.street);
    await fillField(/Mailing Address.*City/i, LLC.mailing.city);
    await page
      .getByLabel(/Mailing Address.*State/i)
      .selectOption(LLC.mailing.state);
    await fillField(/Mailing Address.*ZIP/i, LLC.mailing.zip);
    await nextStep(2000);

    // Step 6: Agent for Service of Process (individual)
    console.error("[step6] selecting Individual agent type");
    await page
      .getByRole("radio", { name: "Individual" })
      .first()
      .click({ force: true });
    await page.waitForTimeout(1500);
    console.error("[step6] filling agent name + address");
    await fillField(/First Name/i, LLC.agent.firstName);
    await fillField(/Last Name/i, LLC.agent.lastName);
    await fillField(/Agent Address.*Address Line 1/i, LLC.agent.street);
    await fillField(/Agent Address.*City/i, LLC.agent.city);
    // Agent state select renders as <select disabled> for ~3s after city fill.
    // Force-enable + set via React's native setter so the form picks it up.
    await page.evaluate((state) => {
      const sel = document.querySelector(
        'select[aria-label="Agent Address: State"]',
      ) as HTMLSelectElement | null;
      if (!sel) throw new Error("Agent state select not found");
      sel.disabled = false;
      const setter = Object.getOwnPropertyDescriptor(
        HTMLSelectElement.prototype,
        "value",
      )!.set!;
      setter.call(sel, state);
      sel.dispatchEvent(new Event("change", { bubbles: true }));
    }, LLC.agent.state);
    await fillField(/Agent Address.*ZIP/i, LLC.agent.zip);
    await nextStep(2000);

    // Step 7: Purpose / Management / File Date
    await page
      .getByRole("radio", { name: "All LLC Member(s)" })
      .first()
      .click({ force: true });
    await page
      .getByRole("radio", {
        name: "Current Date (Most Common) - Document is immediately reviewed and filed.",
      })
      .first()
      .click({ force: true });
    await nextStep(2000);

    // Step 8: Attachments (skipped — none)
    await nextStep(2000);

    // ── Step 9: Review and Signature ──────────────────────────────────
    // Encoded from run-006 trace (turns 2-15):
    //   1. Click "One Signature" radio
    //   2. Click "By signing, I affirm..." checkbox
    //   3. Click "Add" button — opens a dialog
    //   4. In dialog: fill "Organizer Signature" textbox with LLC.organizerName,
    //      click "Today" button (auto-fills date), click "Save"
    //   5. Click Next Step
    console.error(
      "[step9] picking 'One Signature' and opening signature dialog",
    );
    await page
      .getByRole("radio", { name: /^One Signature$/i })
      .first()
      .click({ force: true });
    await page.waitForTimeout(1000);

    // The affirmation checkbox is part of a label that begins "By signing, I affirm".
    // force:true bypasses the styled-label overlay seen elsewhere in this form.
    await page
      .locator("input[type=checkbox]")
      .filter({ has: page.locator(":scope") })
      .last()
      .check({ force: true })
      .catch(async () => {
        // Fallback: click the label text directly
        await page
          .locator("label, span")
          .filter({ hasText: /By signing, I affirm/i })
          .first()
          .click({ force: true });
      });
    await page.waitForTimeout(500);

    await page.getByRole("button", { name: /^Add$/ }).first().click();
    await page.waitForTimeout(1500);

    // Inside the signature dialog. The dialog contains:
    //   - "Organizer Signature" textbox
    //   - Date textbox with placeholder MM/DD/YYYY
    //   - Today button: visible text is "Today" but accessible name is
    //     "Enter today's date for: Date" — we must match the accessible name.
    //   - "Save" button (saves the row, closes dialog)
    console.error("[step9] filling organizer signature:", LLC.organizerName);
    await fillField(/Organizer Signature/i, LLC.organizerName);
    await page.waitForTimeout(500);
    await page
      .getByRole("button", { name: /Enter today'?s date/i })
      .first()
      .click();
    await page.waitForTimeout(500);
    await page
      .getByRole("button", { name: /^Save$/i })
      .first()
      .click();
    await page.waitForTimeout(1500);

    console.error("[step9] advancing to Step 10");
    await nextStep(2000);

    // ── Step 10: Processing Fees ──────────────────────────────────────
    // Per run-006 trace: the "Standard" service radio IS required (the agent
    // initially skipped it, hit "Select standard or expedited processing"
    // error on Step 11, had to come back). Click it explicitly here.
    console.error("[step10] selecting Standard processing service");
    await page
      .getByRole("radio", { name: /^Standard/i })
      .first()
      .click({ force: true });
    await page.waitForTimeout(500);
    console.error("[step10] advancing to Step 11");
    await nextStep(2000);

    // ── Step 11: File Document or Send for Signatures ─────────────────
    // Clicking "File Online" opens a shopping cart panel on the right side.
    console.error("[step11] clicking File Online");
    await page
      .getByRole("button", { name: /^File Online$/i })
      .first()
      .click();
    await page.waitForTimeout(3000);

    // ── Shopping cart panel → Pay with Credit Card ───────────────────
    // The cart shows the LLC line items and a "Pay with Credit Card" button.
    // Clicking it reveals the payment form (in an <aside>).
    console.error("[cart] clicking Pay with Credit Card");
    await page
      .getByRole("button", { name: /Pay with Credit Card/i })
      .first()
      .click();
    await page.waitForTimeout(3000);

    // ── Payment form (in <aside>) ────────────────────────────────────
    // From run-006 turn 59 the form has 12 inputs in this order:
    //   0: FIRST_NAME       3: CC_NUMBER       6: ADDR1        9: POSTAL_CODE
    //   1: LAST_NAME        4: MM/YY           7: ADDR2 (skip) 10: PHONE (skip)
    //   2: COMPANY (skip)   5: CC_CVV          8: CITY         11: PHONE_EXT (skip)
    // Plus an <aside select> for state.
    //
    // Multi-word values (address, city) get truncated by bizfile's autocomplete
    // unless set via the React-native value setter. We use that for all fields
    // for consistency.
    // NOTE: any named function/arrow declared inside page.evaluate gets
    // wrapped with esbuild's `__name(...)` helper when tsx compiles this
    // file, and that helper doesn't exist in the browser context — it
    // throws `ReferenceError: __name is not defined` at runtime. Avoid
    // named function declarations inside page.evaluate; inline the work.
    console.error("[payment] filling 12 fields via React-input bypass");
    await page.evaluate(
      (vals) => {
        const aside = document.querySelector("aside");
        if (!aside) throw new Error("Payment <aside> not found");
        const inputs = aside.querySelectorAll(
          "input[type=text], input[type=tel]",
        ) as NodeListOf<HTMLInputElement>;
        const inputSetter = Object.getOwnPropertyDescriptor(
          HTMLInputElement.prototype,
          "value",
        )?.set;
        if (!inputSetter)
          throw new Error("No value setter on HTMLInputElement");

        // Index → value map. See comment above for index layout.
        //   0: FIRST_NAME       3: CC_NUMBER       6: ADDR1        9: POSTAL_CODE
        //   1: LAST_NAME        4: MM/YY           7: ADDR2 (skip)
        //   2: COMPANY (skip)   5: CC_CVV          8: CITY
        const pairs: Array<[number, string]> = [
          [0, vals.first],
          [1, vals.last],
          [3, vals.card],
          [4, vals.exp],
          [5, vals.cvv],
          [6, vals.addr1],
          [8, vals.city],
          [9, vals.zip],
        ];
        for (const [i, v] of pairs) {
          if (!v) continue;
          const el = inputs[i];
          if (!el)
            throw new Error(
              `Payment input[${i}] not found (have ${inputs.length})`,
            );
          inputSetter.call(el, v);
          el.dispatchEvent(new Event("input", { bubbles: true }));
          el.dispatchEvent(new Event("change", { bubbles: true }));
        }

        // State <select>
        const sel = aside.querySelector("select") as HTMLSelectElement | null;
        if (sel && vals.state) {
          const selSetter = Object.getOwnPropertyDescriptor(
            HTMLSelectElement.prototype,
            "value",
          )?.set;
          if (selSetter) {
            selSetter.call(sel, vals.state);
            sel.dispatchEvent(new Event("change", { bubbles: true }));
          }
        }
      },
      {
        first: PAYMENT.cardholderFirst,
        last: PAYMENT.cardholderLast,
        card: PAYMENT.cardNumber,
        exp: `${PAYMENT.expMonth}/${PAYMENT.expYear}`,
        cvv: PAYMENT.cvv,
        addr1: PAYMENT.billingAddress,
        city: PAYMENT.billingCity,
        state: PAYMENT.billingState,
        zip: PAYMENT.billingZip,
      },
    );

    await page.waitForTimeout(1000);

    // ── STOP. Capture state. Do NOT click the Submit Payment button. ──
    console.error(
      "[payment] all fields populated. STOPPING before submit-payment click.",
    );

    const result: Output = {
      success: false,
      llc_name: "",
      stopped_at_step: "",
      stopped_at_url: "",
      fields_completed: [],
      review_summary: {
        principal_address: "",
        mailing_address: "",
        agent_name: "",
        management_structure: "",
        organizer_name: "",
      },
      payment_summary: {
        cardholder_name: "",
        card_last4: "",
        billing_zip: "",
      },
      filing_fee_shown: "",
      final_submit_button_label: "",
      session_id: bb?.sessionId,
    };

    result.stopped_at_url = page.url();
    await page
      .screenshot({ path: "payment-screen.png", fullPage: true })
      .catch(() => {});

    const safeText = async (sel: string): Promise<string> => {
      try {
        const t = await page
          .locator(sel)
          .first()
          .textContent({ timeout: 2000 });
        return (t ?? "").replace(/\s+/g, " ").trim();
      } catch {
        return "";
      }
    };

    const bodyText =
      (
        await page
          .locator("body")
          .textContent()
          .catch(() => "")
      )
        ?.replace(/\s+/g, " ")
        .slice(0, 4000) ?? "";

    result.stopped_at_step =
      "Payment Screen (Step 11 with payment form filled — all fields populated, awaiting human Submit click)";

    result.llc_name = LLC.name;
    result.review_summary.principal_address = `${LLC.principal.street}, ${LLC.principal.city}, ${LLC.principal.state} ${LLC.principal.zip}`;
    result.review_summary.mailing_address = `${LLC.mailing.street}, ${LLC.mailing.city}, ${LLC.mailing.state} ${LLC.mailing.zip}`;
    result.review_summary.agent_name = `${LLC.agent.firstName} ${LLC.agent.lastName}`;
    result.review_summary.management_structure = "All LLC Member(s)";
    result.review_summary.organizer_name = LLC.organizerName;

    result.payment_summary.cardholder_name = `${PAYMENT.cardholderFirst} ${PAYMENT.cardholderLast}`;
    result.payment_summary.card_last4 = PAYMENT.cardNumber.slice(-4);
    result.payment_summary.billing_zip = PAYMENT.billingZip;

    const feeMatch = bodyText.match(/\$\d{1,4}(?:\.\d{2})?/);
    if (!feeMatch) {
      throw new Error(
        "Payment page loaded, but no filing fee was observed; refusing to report a successful handoff",
      );
    }
    result.filing_fee_shown = feeMatch[0];

    // Capture the label of the button we are deliberately NOT clicking.
    result.final_submit_button_label = await page.evaluate(() => {
      const aside = document.querySelector("aside");
      if (!aside) return "";
      const buttons = Array.from(
        aside.querySelectorAll<HTMLButtonElement>("button"),
      );
      const submit = buttons.find((b) =>
        /pay|submit|file|complete|confirm|place/i.test(b.textContent || ""),
      );
      return submit?.textContent?.trim() ?? "";
    });
    if (!result.final_submit_button_label) {
      throw new Error(
        "Payment fields were filled, but the final submit control was not observed; refusing to hand off an unverified page",
      );
    }

    result.fields_completed = [
      "Step 1: Privacy Warning / Terms and Conditions",
      "Step 2: Submitter Information (skipped — optional)",
      "Step 3: Professional Services (no, skipped)",
      `Step 4: LLC Name (${LLC.name})`,
      "Step 5: Business Addresses (principal + mailing)",
      "Step 6: Agent for Service of Process (Individual)",
      "Step 7: Purpose / Management / File Date",
      "Step 8: Attachments (none)",
      `Step 9: Review and Signature (signed as ${LLC.organizerName})`,
      "Step 10: Processing Fees (Standard service)",
      "Step 11: File Online -> shopping cart -> Pay with Credit Card",
      `Payment form: card ending in ${result.payment_summary.card_last4}, billing ZIP ${PAYMENT.billingZip}`,
    ];

    result.success = true;
    return OutputSchema.parse(result);
  } finally {
    if (bb) {
      // Whether external or self-created, leave the BB session ALIVE on exit.
      // Reason: this script populates the payment form and stops. A HUMAN must
      // click "Submit Payment" in the live-view to actually file the LLC and
      // charge the card. Releasing the session here would kill the browser
      // before they can do that. The session was created with --keep-alive
      // --timeout 1800, so it auto-cleans up in ~30 min if the human doesn't.
      console.error(
        `\n========================================================`,
      );
      console.error(`[playwright] FORM POPULATED. Browser session left alive.`);
      console.error(`[playwright] To file the LLC, click "Submit Payment" in:`);
      console.error(`  https://www.browserbase.com/sessions/${bb.sessionId}`);
      console.error(`Session auto-expires in ~30 min. To release sooner:`);
      console.error(
        `  bb sessions update ${bb.sessionId} --status REQUEST_RELEASE`,
      );
      console.error(
        `========================================================\n`,
      );
      await browser.close().catch(() => {});
    } else {
      await browser.close();
    }
  }
}

main()
  .then((result) => {
    console.log(JSON.stringify(result, null, 2));
    process.exit((result as { success?: boolean })?.success === true ? 0 : 2);
  })
  .catch((err) => {
    console.error("FATAL:", err);
    console.log(JSON.stringify({ success: false, error: String(err) }));
    process.exit(1);
  });
