/**
 * Portal Loader — loads portal definitions from the portals/ directory.
 *
 * Portal definitions are JSON files that describe how to automate a
 * specific biller portal. They are generated by Claude Code using the
 * agent-browse skill (exploring the portal interactively) and then
 * saved here for the job runner to execute deterministically.
 *
 * This is the key insight for Spend Workflow:
 *   1. Claude Code + agent-browse explores the portal → generates definition
 *   2. Engineer reviews/tweaks the definition
 *   3. Job runner executes it reliably at scale
 */

import { readFileSync, readdirSync, existsSync } from "fs";
import { join, resolve } from "path";
import type { PortalDefinition } from "./types.js";

const PORTALS_DIR = resolve(import.meta.dirname ?? ".", "../portals");

// Cache loaded portals
const portalCache = new Map<string, PortalDefinition>();

/**
 * Load all portal definitions from the portals/ directory.
 */
export function loadAllPortals(): Map<string, PortalDefinition> {
  if (portalCache.size > 0) return portalCache;

  if (!existsSync(PORTALS_DIR)) {
    console.warn(`Portals directory not found: ${PORTALS_DIR}`);
    return portalCache;
  }

  const files = readdirSync(PORTALS_DIR).filter((f) => f.endsWith(".json"));

  for (const file of files) {
    try {
      const content = readFileSync(join(PORTALS_DIR, file), "utf-8");
      const portal = JSON.parse(content) as PortalDefinition;
      portalCache.set(portal.id, portal);

      // Also index by login URL for lookup
      portalCache.set(normalizeUrl(portal.loginUrl), portal);

      console.log(`Loaded portal: ${portal.name} (${portal.id})`);
    } catch (err) {
      console.error(`Failed to load portal from ${file}:`, err);
    }
  }

  return portalCache;
}

/**
 * Find a portal definition by URL or ID.
 */
export function loadPortal(portalUrlOrId: string): PortalDefinition | null {
  // Ensure portals are loaded
  loadAllPortals();

  // Try exact ID match
  const byId = portalCache.get(portalUrlOrId);
  if (byId) return byId;

  // Try URL match
  const normalized = normalizeUrl(portalUrlOrId);
  const byUrl = portalCache.get(normalized);
  if (byUrl) return byUrl;

  // Try fuzzy match on domain
  const domain = extractDomain(portalUrlOrId);
  for (const [, portal] of portalCache) {
    if (extractDomain(portal.loginUrl) === domain) {
      return portal;
    }
  }

  return null;
}

function normalizeUrl(url: string): string {
  try {
    const parsed = new URL(url);
    return `${parsed.hostname}${parsed.pathname}`.replace(/\/$/, "");
  } catch {
    return url.toLowerCase();
  }
}

function extractDomain(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url.toLowerCase();
  }
}
