import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire,stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';
const require=createRequire(import.meta.url),{z}=require(process.env.ZOD_MODULE_PATH || 'zod');
const source=readFileSync(process.env.ATS_SOURCE_PATH || new URL('../company-intel.ts',import.meta.url),'utf8');
const start=source.includes('function atsVendorFromUrl(')?source.indexOf('function atsVendorFromUrl('):source.indexOf('async function detectATS(');
const fragment=source.slice(start,source.indexOf('async function findPersonMentions('));
const scope=vm.createContext({URL,z,console:{log(){}}});vm.runInContext(stripTypeScriptTypes(fragment)+'\nglobalThis.detect=detectATS;globalThis.vendor=typeof atsVendorFromUrl === "function"?atsVendorFromUrl:undefined;',scope);
for(const [url,expected] of [['https://jobs.lever.co/company','Lever'],['https://LEVER.CO/company','Lever'],['https://boards.greenhouse.io/company','Greenhouse'],['https://example.myworkdayjobs.com/jobs','ERP platform'],['https://lever.co.synthetic.invalid/',null],['https://evil-lever.co/',null],['https://synthetic.invalid/?next=lever.co',null],['https://synthetic.invalid/lever.co',null],['https://lever.co@synthetic.invalid/',null],['https://user@lever.co/',null],['javascript:lever.co',null],['https://lever.co:444/',null]])test('vendor hostname '+url,()=>assert.equal(scope.vendor(url),expected));
async function detect(options={}){let extracted=0;let current='https://company.invalid';const page={goto:async url=>{current=options.current??url;return {status:()=>options.status??404};},url:async()=>current,waitForTimeout:async()=>{},evaluate:async()=>({isCareers:options.careers??true,urls:options.urls??[]})};
 const result=await scope.detect({browser:{context:{activePage:async()=>page}},act:async()=>({data:{success:options.action??true}}),extract:async()=>{extracted++;return {data:{count:options.count??0}};}},'company.invalid');return {result,extracted};}
test('failed navigation plus lookalike hostname remains unknown',async()=>{const {result,extracted}=await detect({action:false,current:'https://lever.co.synthetic.invalid/'});assert.equal(result.ats.ats_detected,null);assert.equal(result.ats.careers_url,null);assert.equal(extracted,0);});
test('successful action on a non-careers shell is not discovery',async()=>{const {result}=await detect({current:'https://jobs.lever.co/company',careers:false});assert.equal(result.ats.ats_detected,null);});
test('direct successful path captures actual redirected URL with observed careers heading',async()=>{const {result}=await detect({action:false,status:200,current:'https://jobs.lever.co/company'});assert.equal(result.ats.ats_detected,'Lever');assert.equal(result.ats.careers_url,'https://jobs.lever.co/company');assert.ok(result.ats.evidence.includes('vendor-domain signal'));});
test('substring in a successfully observed careers URL still gives unknown',async()=>{const {result}=await detect({current:'https://company.invalid/careers?provider=lever.co'});assert.equal(result.ats.ats_detected,null);});
test('observed job links support vendor signals but conflicting vendors stay unknown',async()=>{const one=await detect({urls:['https://jobs.ashbyhq.com/company']});assert.equal(one.result.ats.ats_detected,'Ashby');const conflict=await detect({urls:['https://jobs.ashbyhq.com/company','https://jobs.lever.co/company']});assert.equal(conflict.result.ats.ats_detected,null);});
test('invalid role count remains unknown',async()=>{const {result}=await detect({count:-1});assert.equal(result.ats.open_roles_count,null);});
