import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import vm from 'node:vm';
const source=readFileSync(process.env.LOGIN_SOURCE_PATH || new URL('../run.ts',import.meta.url),'utf8');const attempt=source.slice(source.indexOf('async function attemptOnce'),source.indexOf('async function runSite'));
const helperStart=source.includes('function authenticatedObservation')?source.indexOf('function authenticatedObservation'):source.indexOf('function isWall');const helpers=source.slice(helperStart,source.indexOf('function detectedSummary'));
async function run(options={}){let actions=0,observations=0,closed=0,clock=0;const pre={loginFormVisible:true,loginEntryVisible:true,captchaVisible:false,blockingMessage:null,summary:'Synthetic login'};const post={loginFormVisible:false,loginEntryVisible:false,captchaVisible:false,blockingMessage:null,summary:'Synthetic loading',...options.post};const page={goto:async()=>{},url:async()=> options.url??'https://synthetic.invalid/',screenshot:async()=>{}};const stagehand={browser:{sessionId:options.sessionId,context:{pages:async()=>[page]},close:async()=>{closed++;}},act:async()=>({data:{success:++actions!==(options.fail??-1)}}),close:async()=>{closed++;}};
 const ctx=vm.createContext({URL,Date:{now:()=>clock+=1000},PROFILES:{baseline:{}},Stagehand:{create:async()=>stagehand},StagehandCreateOptionsSchema:{parse:v=>v},browserbase:{launch:async()=>({})},process:{env:{}},sessionParams:()=>({}),MODEL:'synthetic',console:{log(){}},sleep:async()=>{},snap:async()=>'synthetic.png',identifyAntibot:async()=>({vendors:[]}),observe:async()=>++observations===1?pre:post,safeUrl:()=> 'https://synthetic.invalid/',credsFor:()=>options.noCredentials?null:{username:'synthetic-user',password:'synthetic-password'},detectedSummary:()=>'',SOLVE_WAIT_MS:2000});vm.runInContext(stripTypeScriptTypes(helpers+source.slice(source.includes('function httpEvidenceUrl')?source.indexOf('function httpEvidenceUrl'):source.indexOf('function safeUrl'),source.indexOf('async function attemptOnce'))+attempt)+'\nglobalThis.run=attemptOnce;',ctx);const result=await ctx.run({id:'synthetic',label:'Synthetic',url:'https://synthetic.invalid',settleMs:0,usernameField:'username',passwordField:'password',submitButton:'submit'},'baseline',1);return {result,actions,closed};}
for(const fail of [1,2,3])test('action failure stops login sequence at '+fail,async()=>{const f=await run({fail});assert.equal(f.actions,fail);assert.notEqual(f.result.verdict,'login_succeeded');assert.equal(f.closed,2);});
for(const post of [{},{loginFormVisible:true,loginEntryVisible:true},{authenticatedControlsVisible:true,loginEntryVisible:true},{authenticatedControlsVisible:true,captchaVisible:true}])test('ambiguous or contradictory observation cannot succeed '+JSON.stringify(post),async()=>{const f=await run({post});assert.notEqual(f.result.verdict,'login_succeeded');});
test('successful actions plus positive controls can report observed login',async()=>{const f=await run({post:{authenticatedControlsVisible:true}});assert.equal(f.result.verdict,'login_succeeded');assert.equal(f.actions,3);});
test('without credentials only reachability is reported',async()=>{const f=await run({noCredentials:true});assert.equal(f.result.verdict,'reached_login');assert.equal(f.actions,0);});
for(const dom of [false,true,'error'])test('actual observe overrides model authentication claim with DOM evidence: '+dom,async()=>{const fragment=source.slice(source.indexOf('function authenticatedLoginControls()'),source.indexOf('function isWall('));const c=vm.createContext({Observation:{}});vm.runInContext(stripTypeScriptTypes(fragment)+'\nglobalThis.observe=observe;',c);const observation=await c.observe({extract:async()=>({data:{authenticatedControlsVisible:true}}),browser:{context:{pages:async()=>[{evaluate:async()=>{if(dom==='error')throw Error('synthetic');return dom;}}]}}});assert.equal(observation.authenticatedControlsVisible,dom===true);});

test('actual attempt serializes awaited URL and supported browser session ID',async()=>{const f=await run({noCredentials:true,sessionId:'synthetic-session',url:'https://synthetic.invalid/final'});const saved=JSON.parse(JSON.stringify(f.result));assert.equal(saved.finalUrl,'https://synthetic.invalid/final');assert.equal(saved.sessionId,'synthetic-session');assert.equal(saved.sessionReplayUrl,'https://www.browserbase.com/sessions/synthetic-session');assert.equal(saved.liveViewUrl,null);});
