import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import test from 'node:test';
import {uploadBill} from '../upload-bill.mjs';
import {loadReviewedBill,validateReviewedBill} from '../reviewed-bill.mjs';
const pdf=Buffer.from('%PDF-1.4\nSynthetic invoice fixture; no real document.\n%%EOF');
function record(){return {document:{sha256:createHash('sha256').update(pdf).digest('hex')},review:{reviewer:'Synthetic Reviewer',reviewedAt:'2026-09-01T00:00:00.000Z',confirmedFieldsMatchDocument:true},bill:{vendorName:'Synthetic County Treasurer',vendorAddress:{address_line_1:'123 Example Road',city:'Example',state:'CA',postal_code:'01234',country:'US'},vendorEmail:'treasurer@example.com',invoiceNumber:'0000123',amount:'123.45',currency:'USD',issuedAt:'2026-08-01',dueAt:'2026-12-01',propertyAddress:'456 Example Avenue',parcelId:'000-123-456',taxPeriod:'2026 synthetic annual installment'}};}
async function fixture(t,mutate=()=>{},bytes=pdf){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cookbook-r179-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const data=record();mutate(data);const pdfPath=path.join(dir,'invoice.pdf'),recordPath=path.join(dir,'review.json');await fs.writeFile(pdfPath,bytes);await fs.writeFile(recordPath,JSON.stringify(data));return {dir,pdfPath,recordPath,data};}
function transport(options={}){const calls=[];return {calls,fetchImpl:async(url,request)=>{calls.push({url,request});if(options.before)await options.before(url);let data;if(url.endsWith('/token'))data={access_token:'SYNTHETIC_TOKEN'};else if(url.endsWith('/entities'))data={data:[{id:'synthetic-entity',is_primary:true}]};else if(url.includes('/vendors?'))data={data:options.existing?[{id:'synthetic-vendor',name:'Synthetic County Treasurer'}]:[]};else if(url.endsWith('/vendors'))data={id:'synthetic-vendor'};else if(url.endsWith('/attachments')){if(options.attachError)return {ok:false,status:500};data={id:'synthetic-attachment'};}else data={id:'synthetic-bill'};return {ok:true,json:async()=>data};}};}
const env={AP_ACCESS_TOKEN:'SYNTHETIC_TOKEN',AP_API_BASE_URL:'https://ap.example.invalid'};
test('reviewed metadata drives vendor, invoice, memos and exact attachment bytes',async t=>{const f=await fixture(t),http=transport();const result=await uploadBill({...f,env,fetchImpl:http.fetchImpl});assert.equal(result.mode,'draft');assert.equal(result.environment,'sandbox');assert.ok(http.calls.every(c=>c.url.startsWith('https://ap.example.invalid/')));const created=http.calls.find(c=>c.url.endsWith('/bills/drafts'));const body=JSON.parse(created.request.body);assert.equal(body.invoice_number,'0000123');assert.equal(body.line_items[0].amount,'123.45');assert.equal(body.issued_at,f.data.bill.issuedAt);assert.equal(body.due_at,f.data.bill.dueAt);for(const field of ['propertyAddress','parcelId','taxPeriod'])assert.ok(body.memo.includes(f.data.bill[field]));assert.equal(body.line_items[0].memo,body.memo);const attachment=http.calls.at(-1).request.body.get('file');assert.deepEqual(Buffer.from(await attachment.arrayBuffer()),pdf);assert.ok(http.calls.some(c=>c.url.endsWith('/vendors')&&JSON.parse(c.request.body).name===f.data.bill.vendorName));});
const invalids=[['digest',r=>r.document.sha256='0'.repeat(64)],['review',r=>r.review.confirmedFieldsMatchDocument=false],['reviewer',r=>r.review.reviewer=''],['review timestamp',r=>r.review.reviewedAt='not-a-date'],['future review',r=>r.review.reviewedAt='2999-01-01T00:00:00.000Z'],['invoice',r=>r.bill.invoiceNumber=''],['numeric invoice',r=>r.bill.invoiceNumber=123],['amount number',r=>r.bill.amount=123.45],['scientific amount',r=>r.bill.amount='1e3'],['negative amount',r=>r.bill.amount='-1.00'],['zero amount',r=>r.bill.amount='0.00'],['fractional cent',r=>r.bill.amount='1.001'],['currency',r=>r.bill.currency='EUR'],['bad date',r=>r.bill.issuedAt='2026-02-30'],['due order',r=>r.bill.dueAt='2025-01-01'],['parcel',r=>r.bill.parcelId=''],['property',r=>r.bill.propertyAddress=''],['tax period',r=>r.bill.taxPeriod=''],['vendor email',r=>r.bill.vendorEmail='invalid'],['unknown field',r=>r.bill.memo='unreviewed'],['missing field',r=>delete r.bill.vendorAddress]];
for(const [label,mutate] of invalids)test(`${label} rejected before all HTTP calls`,async t=>{const f=await fixture(t,mutate),http=transport();await assert.rejects(uploadBill({...f,env,fetchImpl:http.fetchImpl}));assert.equal(http.calls.length,0);});
test('non-PDF rejected before authentication',async t=>{const f=await fixture(t,()=>{},Buffer.from('not PDF')),http=transport();await assert.rejects(uploadBill({...f,env,fetchImpl:http.fetchImpl}),/PDF header/);assert.equal(http.calls.length,0);});
test('oversized PDF rejected before authentication',async t=>{const f=await fixture(t);await fs.truncate(f.pdfPath,25*1024*1024+1);const http=transport();await assert.rejects(uploadBill({...f,env,fetchImpl:http.fetchImpl}),/size limit/);assert.equal(http.calls.length,0);});
test('invalid JSON does not disclose its text',async t=>{const f=await fixture(t);await fs.writeFile(f.recordPath,'PRIVATE_SYNTHETIC_BAD_JSON');await assert.rejects(loadReviewedBill(f.pdfPath,f.recordPath),error=>!error.message.includes('PRIVATE_SYNTHETIC'));});
test('file replacement after validation cannot change attachment',async t=>{const f=await fixture(t),http=transport({before:async()=>fs.writeFile(f.pdfPath,'%PDF-1.4\nReplacement')});await uploadBill({...f,env,fetchImpl:http.fetchImpl});assert.deepEqual(Buffer.from(await http.calls.at(-1).request.body.get('file').arrayBuffer()),pdf);});
test('new reviewed metadata replaces all previous property and amount values',async t=>{const f=await fixture(t,r=>{r.bill.amount='321.00';r.bill.invoiceNumber='0000999';r.bill.propertyAddress='789 Different Street';r.bill.parcelId='0000999';r.bill.taxPeriod='Different reviewed period';}),http=transport({existing:true});await uploadBill({...f,env,fetchImpl:http.fetchImpl});const body=JSON.parse(http.calls.find(c=>c.url.endsWith('/bills/drafts')).request.body);assert.equal(body.invoice_number,'0000999');assert.equal(body.line_items[0].amount,'321.00');assert.ok(body.memo.includes('789 Different Street'));assert.ok(!body.memo.includes('456 Example Avenue'));});
test('submitted mode requires explicit flag before any HTTP calls',async t=>{const f=await fixture(t),http=transport();await assert.rejects(uploadBill({...f,env:{...env,AP_BILL_MODE:'bill'},fetchImpl:http.fetchImpl}),/AP_ALLOW_SUBMIT_BILL/);assert.equal(http.calls.length,0);});
test('explicit submitted mode uses submitted endpoint and attachment',async t=>{const f=await fixture(t),http=transport();await uploadBill({...f,env:{...env,AP_BILL_MODE:'bill',AP_ALLOW_SUBMIT_BILL:'true'},fetchImpl:http.fetchImpl});assert.ok(http.calls.some(c=>c.url.endsWith('/bills')));assert.ok(http.calls.at(-1).url.endsWith('/bills/synthetic-bill/attachments'));});
test('invalid environment rejected',async t=>{const f=await fixture(t),http=transport();await assert.rejects(uploadBill({...f,env:{...env,AP_ENV:'typo'},fetchImpl:http.fetchImpl}),/AP_ENV/);assert.equal(http.calls.length,0);});
test('attachment failure identifies created bill and warns against duplicate creation',async t=>{const f=await fixture(t),http=transport({attachError:true});await assert.rejects(uploadBill({...f,env,fetchImpl:http.fetchImpl}),/synthetic-bill.*unconfirmed.*duplicate/);assert.equal(http.calls.filter(c=>c.url.endsWith('/bills/drafts')).length,1);});
test('client credential flow follows successful document validation',async t=>{const f=await fixture(t),http=transport();await uploadBill({...f,env:{...env,AP_ACCESS_TOKEN:'',AP_CLIENT_ID:'SYNTHETIC_ID',AP_CLIENT_SECRET:'SYNTHETIC_SECRET'},fetchImpl:http.fetchImpl});assert.ok(http.calls[0].url.endsWith('/token'));});
test('bill metadata snapshot does not retain mutable record references',()=>{const input=record();const bill=validateReviewedBill(input,pdf);input.bill.vendorAddress.city='Changed';assert.equal(bill.vendorAddress.city,'Example');});
test('oversized review record rejected before HTTP calls',async t=>{const f=await fixture(t),http=transport();await fs.writeFile(f.recordPath,' '.repeat(65537));await assert.rejects(uploadBill({...f,env,fetchImpl:http.fetchImpl}),/64 KiB/);assert.equal(http.calls.length,0);});
test('committed example is synthetic and cannot pass as a completed review',async()=>{const example=JSON.parse(await fs.readFile(new URL('../reviewed-bill.example.json',import.meta.url),'utf8'));assert.equal(example.review.confirmedFieldsMatchDocument,false);assert.throws(()=>validateReviewedBill(example,pdf));});
