import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import {deflateRawSync,crc32} from 'node:zlib';
import test from 'node:test';
import {readDownloadZip} from '../shared/download-zip.ts';
const root=new URL('../',import.meta.url);
function zip(entries=[],options={}){const locals=[],centrals=[];let offset=0;for(const [name,text] of entries){const filename=Buffer.from(name),data=Buffer.from(text),compressed=options.deflate?deflateRawSync(data):data,checksum=crc32(data),flags=2048|(options.descriptor?8:0);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(flags,6);local.writeUInt16LE(options.deflate?8:0,8);if(!options.descriptor){local.writeUInt32LE(checksum,14);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(data.length,22);}local.writeUInt16LE(filename.length,26);let descriptor=Buffer.alloc(0);if(options.descriptor){descriptor=Buffer.alloc(options.unsigned?12:16);let d=0;if(!options.unsigned){descriptor.writeUInt32LE(0x08074b50);d=4;}descriptor.writeUInt32LE(checksum,d);descriptor.writeUInt32LE(compressed.length,d+4);descriptor.writeUInt32LE(data.length,d+8);}const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(flags,8);central.writeUInt16LE(options.deflate?8:0,10);central.writeUInt32LE(checksum,16);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(filename.length,28);central.writeUInt32LE(offset,42);const localRecord=Buffer.concat([local,filename,compressed,descriptor]);locals.push(localRecord);centrals.push(central,filename);offset+=localRecord.length;}const directory=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,directory,end]);}
const code=fs.readFileSync(process.env.COOKBOOK_R183_BASELINE||new URL('shared/deliver.ts',root),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
const ctx=vm.createContext({readDownloadZip,Buffer,TextDecoder,Uint8Array,AbortController,Date,setTimeout,clearTimeout});vm.runInContext(stripTypeScriptTypes(code),ctx);
function transport(snapshots){let calls=0;return {get calls(){return calls;},sessions:{downloads:{list:async()=>{const current=snapshots[Math.min(calls++,snapshots.length-1)];if(current instanceof Error)throw current;return new Response(current);}}}};}
const opts={timeoutMs:40,intervalMs:1};
function page(){return {triggers:[],async evaluate(fn,args){this.triggers.push(args);}};}
for(const options of [{},{deflate:true},{descriptor:true},{deflate:true,descriptor:true},{deflate:true,descriptor:true,unsigned:true}])test(`valid archive variant ${JSON.stringify(options)}`,()=>{const entries=readDownloadZip(zip([['folder/desired.csv','a,b\r\n1,2\r\n'],['other.txt','hello']],options));assert.equal(entries.length,2);assert.equal(entries[0].data.toString(),'a,b\r\n1,2\r\n');});
test('empty archive is valid but not a native download',async()=>{assert.equal(readDownloadZip(zip()).length,0);await assert.rejects(ctx.waitForDownloadZip(transport([zip()]),'synthetic',opts));});
for(const [label,mutate] of [['truncated',b=>b.subarray(0,-1)],['CRC',b=>{b[30+'desired.csv'.length]^=1;return b;}],['unsupported method',b=>{b.writeUInt16LE(12,8);return b;}],['encrypted',b=>{b.writeUInt16LE(2049,6);return b;}],['local name mismatch',b=>{b[30]=88;return b;}],['missing central directory',b=>b.subarray(0,40)],['archive too large',()=>Buffer.alloc(25*1024*1024+1)]])test(`reject ${label}`,()=>{assert.throws(()=>readDownloadZip(mutate(zip([['desired.csv','synthetic']]))));});
for(const name of ['../desired.csv','/desired.csv','a\\desired.csv','a/../desired.csv','C:/desired.csv'])test(`reject unsafe entry ${name}`,()=>{assert.throws(()=>readDownloadZip(zip([[name,'x']])));});
test('reject duplicate archive paths',()=>{assert.throws(()=>readDownloadZip(zip([['desired.csv','x'],['desired.csv','y']])));});
test('suffix selection cannot fall back to unrelated or ambiguous file',()=>{assert.throws(()=>ctx.readZipEntry(zip([['other.txt','x']]),'.csv'));assert.throws(()=>ctx.readZipEntry(zip([['a.csv','x'],['b.csv','y']]),'.csv'));});
test('native reader decodes exactly the selected CSV',()=>{assert.equal(ctx.readZipEntry(zip([['other.txt','x'],['source.csv','hello']])).text,'hello');});
test('old unrelated download cannot confirm delivery',async()=>{const bb=transport([zip(),zip([['raw-export.csv','raw,data']])]),p=page();await assert.rejects(ctx.deliverCsv(p,bb,'synthetic','mapped.csv','mapped,data',opts));assert.equal(p.triggers.length,1);});
test('wrong content under expected filename cannot confirm delivery',async()=>{await assert.rejects(ctx.deliverCsv(page(),transport([zip(),zip([['mapped.csv','wrong']])]),'synthetic','mapped.csv','expected',opts));});
test('preexisting filename is rejected before triggering a new download',async()=>{const p=page();await assert.rejects(ctx.deliverCsv(p,transport([zip([['mapped.csv','expected']])]),'synthetic','mapped.csv','expected',opts),/already exists/);assert.equal(p.triggers.length,0);});
test('delivery waits through stale and corrupt snapshots for exact new file bytes',async()=>{const expected='name,value\r\nSynthetic,é\r\n';const final=zip([['raw.csv','raw'],['folder/mapped.csv',expected]],{deflate:true,descriptor:true});const bb=transport([zip([['raw.csv','raw']]),zip([['raw.csv','raw']]),final.subarray(0,-3),final]);const p=page();assert.equal(await ctx.deliverCsv(p,bb,'synthetic','mapped.csv',expected,opts),final.length);assert.equal(bb.calls,4);assert.equal(p.triggers[0].name,'mapped.csv');assert.equal(p.triggers[0].text,expected);});
test('duplicate basenames cannot confirm a uniquely named delivery',async()=>{await assert.rejects(ctx.deliverCsv(page(),transport([zip(),zip([['one/mapped.csv','expected'],['two/mapped.csv','expected']])]),'synthetic','mapped.csv','expected',opts));});
test('invalid target name fails before network or browser interaction',async()=>{const bb=transport([zip()]),p=page();await assert.rejects(ctx.deliverCsv(p,bb,'synthetic','../mapped.csv','x',opts));assert.equal(bb.calls,0);assert.equal(p.triggers.length,0);});
test('request deadline aborts an unresolved SDK request',async()=>{let signal;const bb={sessions:{downloads:{list:async(_,options)=>{signal=options.signal;return new Promise(()=>{});}}}};await assert.rejects(ctx.waitForDownloadZip(bb,'synthetic',{timeoutMs:15,intervalMs:1}));assert.equal(signal.aborted,true);});
test('declared inflated size over the entry limit is rejected',()=>{const b=zip([['desired.csv','x']],{deflate:true});const central=b.readUInt32LE(b.length-6);b.writeUInt32LE(20*1024*1024+1,central+24);assert.throws(()=>readDownloadZip(b));});
test('too many entries are rejected before parsing them',()=>{const b=zip();b.writeUInt16LE(1001,8);b.writeUInt16LE(1001,10);assert.throws(()=>readDownloadZip(b));});
test('bad data descriptor cannot confirm file content',()=>{const b=zip([['desired.csv','x']],{descriptor:true});const central=b.readUInt32LE(b.length-6);b[central-12]^=1;assert.throws(()=>readDownloadZip(b));});
async function notesCaller(success){const rawZip=zip([['raw-export.csv','synthetic raw']]);const finalZip=zip([['raw-export.csv','synthetic raw'],['client-notes.csv','synthetic mapped']]);const bb=transport(success?[rawZip,rawZip,finalZip]:[rawZip]),p=page();let handler,closed=0;const context=vm.createContext({defineFn:(_,fn)=>handler=fn,workflowParams:{},BROWSERBASE_API_KEY:'synthetic',SQUARE_CUSTOMER_NOTES_CONTEXT_ID:'synthetic',runSessionTask:async()=>({success:true}),openSquareSession:async()=>({bb,page:p,sessionId:'synthetic',close:async()=>{closed++;}}),clientNotesCsv:()=>({rows:1,csv:'synthetic mapped'}),readZipEntry:ctx.readZipEntry,waitForDownloadZip:(b,s)=>ctx.waitForDownloadZip(b,s,opts),deliverCsv:(...args)=>ctx.deliverCsv(...args,opts)});const source=fs.readFileSync(new URL('functions/customer-notes.ts',root),'utf8').replace(/^import[\s\S]*?from\s+["'][^"']+["'];\s*/gm,'');vm.runInContext(stripTypeScriptTypes(source),context);return {result:await handler({session:{id:'synthetic'}}),closed};}
test('actual notes handler does not claim mapped success from its raw export',async()=>{const {result,closed}=await notesCaller(false);assert.equal(result.ok,false);assert.equal(result.mapped,false);assert.equal(closed,1);});
test('actual notes handler confirms exact mapped artifact alongside raw export',async()=>{const {result,closed}=await notesCaller(true);assert.equal(result.ok,true);assert.equal(result.mapped,true);assert.equal(closed,1);});
test('supports the SDK Node-stream response body as well as native Web streams',async()=>{const {Readable}=await import('node:stream');const archive=zip([['native.csv','synthetic']]);const bb={sessions:{downloads:{list:async()=>({body:Readable.from([archive.subarray(0,10),archive.subarray(10)])})}}};assert.equal((await ctx.waitForDownloadZip(bb,'synthetic',opts)).byteLength,archive.length);});
