// Node 24: node --test tests/browse-stream.test.mjs. No network or dependencies.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
const source=stripTypeScriptTypes(fs.readFileSync(new URL('../src/app/browse-stream.ts',import.meta.url),'utf8'));
const {consumeBrowseStream,BrowseStreamError}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const encode=new TextEncoder();
const frame=entry=>'data: '+JSON.stringify(entry)+'\n\n';
const done=outcome=>frame({type:'done',message:'Synthetic done',outcome});
const status=frame({type:'status',message:'Synthetic progress'});
const listing={address:'Synthetic',price:'1',beds:'1',baths:'1',sqft:'1',link:'https://example.invalid',details:'Synthetic'};
function response(text,options={}){return new Response(text,{headers:{'content-type':'text/event-stream'},...options});}
const rejection=outcome=>error=>error instanceof BrowseStreamError&&error.outcome===outcome&&!error.message.includes('PRIVATE');
for(const [name,r] of [['HTTP500',()=>response('PRIVATE',{status:500})],['wrong content type',()=>response('PRIVATE',{headers:{'content-type':'text/html'}})],['no body',()=>response(null)]])test(`${name} rejects without exposing response body`,async()=>{await assert.rejects(consumeBrowseStream(r(),()=>{}),rejection('error'));});
for(const [name,text] of [['empty',''],['status',status],['session',frame({type:'session',message:'Synthetic',sessionId:'id',debugUrl:'https://example.invalid'})],['result',frame({type:'result',message:'Synthetic',data:[listing]})],['partial frame','data: {"type":']])test(`EOF after ${name} is interrupted`,async()=>{await assert.rejects(consumeBrowseStream(response(text),()=>{}),rejection('interrupted'));});
for(const [wire,outcome] of [['completed','completed'],['error','error'],['incomplete','interrupted']])test(`explicit done ${wire} returns ${outcome}`,async()=>{const entries=[];assert.equal(await consumeBrowseStream(response(done(wire)),e=>entries.push(e)),outcome);assert.equal(entries.length,1);});
test('prior error cannot become completed',async()=>{const entries=[];assert.equal(await consumeBrowseStream(response(frame({type:'error',message:'Synthetic failure'})+done('completed')),e=>entries.push(e)),'error');assert.equal(entries.at(-1).outcome,'error');});
test('done is not delivered before EOF and later data invalidates it',async()=>{let controller;const entries=[];const stream=new ReadableStream({start(c){controller=c;}});const pending=consumeBrowseStream(response(stream),e=>entries.push(e));controller.enqueue(encode.encode(done('completed')));await new Promise(r=>setImmediate(r));assert.equal(entries.length,0);controller.enqueue(encode.encode(status));controller.close();await assert.rejects(pending,rejection('error'));assert.equal(entries.length,0);});
test('single-byte UTF8 chunks, CRLF, comments and multiline data parse correctly',async()=>{const text=': keepalive\r\n\r\ndata: {"type":"status",\r\ndata: "message":"Synthetic 🦊 café"}\r\n\r\n'+done('completed').replaceAll('\n','\r\n');const bytes=encode.encode(text);let index=0;const stream=new ReadableStream({pull(c){if(index===bytes.length)c.close();else {c.enqueue(bytes.slice(index,index+1));index++;}}});const entries=[];assert.equal(await consumeBrowseStream(response(stream),e=>entries.push(e)),'completed');assert.equal(entries[0].message,'Synthetic 🦊 café');});
for(const [name,text] of [['malformed JSON','data: PRIVATE\n\n'],['unknown type',frame({type:'bogus',message:'Synthetic'})],['wrong message',frame({type:'status',message:1})],['missing outcome',frame({type:'done',message:'Synthetic'})],['bad outcome',done('bogus')],['bad session',frame({type:'session',message:'Synthetic',sessionId:2})],['bad listing',frame({type:'result',message:'Synthetic',data:[{...listing,price:1}]})],['missing listing',frame({type:'result',message:'Synthetic'})],['bad step',frame({type:'step',message:'Synthetic',step:-1})],['postterminal partial',done('completed')+'data: {']])test(`${name} fails closed`,async()=>{await assert.rejects(consumeBrowseStream(response(text),()=>{}),rejection('error'));});
test('invalid UTF8 rejects',async()=>{await assert.rejects(consumeBrowseStream(response(new Uint8Array([0xff])),()=>{}),rejection('error'));});
test('oversized event rejects and cancels the source',async()=>{let cancelled=false;const stream=new ReadableStream({start(c){c.enqueue(encode.encode('data: '+ 'x'.repeat(1024*1024)));},cancel(){cancelled=true;}});await assert.rejects(consumeBrowseStream(response(stream),()=>{}),rejection('error'));assert.equal(cancelled,true);assert.equal(stream.locked,false);});
test('total stream bound also covers comment-only traffic',async()=>{let cancelled=false;const chunk=encode.encode(':'+ 'x'.repeat(100000)+'\n\n');let n=0;const stream=new ReadableStream({pull(c){if(n++<100)c.enqueue(chunk);else c.close();},cancel(){cancelled=true;}});await assert.rejects(consumeBrowseStream(response(stream),()=>{}),rejection('error'));assert.equal(cancelled,true);});
test('transport read failure after progress stays interrupted and unlocks reader',async()=>{let n=0;const stream=new ReadableStream({pull(c){if(n++===0)c.enqueue(encode.encode(status));else c.error(Error('PRIVATE'));}});const entries=[];await assert.rejects(consumeBrowseStream(response(stream),e=>entries.push(e)),rejection('interrupted'));assert.equal(entries.length,1);assert.equal(stream.locked,false);});
test('malformed input cancels rather than leaving an open reader',async()=>{let cancelled=false;const stream=new ReadableStream({start(c){c.enqueue(encode.encode('data: PRIVATE\n\n'));},cancel(){cancelled=true;}});await assert.rejects(consumeBrowseStream(response(stream),()=>{}),rejection('error'));assert.equal(cancelled,true);assert.equal(stream.locked,false);});

test('session ID without optional debug URL is delivered before interrupted EOF',async()=>{const entries=[];await assert.rejects(consumeBrowseStream(response(frame({type:'session',message:'Synthetic',sessionId:'synthetic'})),e=>entries.push(e)),rejection('interrupted'));assert.equal(entries[0].sessionId,'synthetic');});
