import assert from 'node:assert/strict';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import test from 'node:test';
const {z}=await import(process.env.COOKBOOK_ZOD_MODULE || 'zod');
const root=new URL('../src/',import.meta.url);
const product=()=>({title:'Synthetic product title',price:'$12.00',originalPrice:null,rating:'4.6',reviewCount:null,unitsSold:null,storeName:null,shipsTo:null,specs:[{name:'Material',value:'Synthetic'}]});
function load(file,extra={}){const source=fs.readFileSync(file,'utf8').replace(/^import[\s\S]*?from\s+["'][^"']+["'];\s*/gm,'').replace(/^export /gm,'');const context=vm.createContext({z,CONFIG:{inlineWaitMs:1},safeHost:url=>new URL(url).hostname,URL,...extra});vm.runInContext(stripTypeScriptTypes(source),context);return context;}
function ali(options={}){let calls=0;const context=load(process.env.COOKBOOK_R175_BASELINE||new URL('capture/aliexpress.ts',root));const adapter=vm.runInContext('aliexpressAdapter',context);const page={async waitForFunction(){if(options.waitError)throw Error('synthetic timeout');},async evaluate(){return options.noTitle?'':'Synthetic rendered product';}};const stagehand={async extract(instruction,schema){calls++;assert.equal(typeof instruction,'string');assert.equal(schema.safeParse(product()).success,true);if(options.error)throw Error('SYNTHETIC_PRIVATE_PROVIDER_DETAIL');return options.response===undefined?{data:product(),metadata:{tokens:1}}:options.response;}};return {context,adapter,page,stagehand,get calls(){return calls},collect(ctx={parse:true,stagehand}){return adapter.arm().collect(page,ctx);}};}
test('AliExpress raw-only capture never calls extraction',async()=>{const f=ali();const result=await f.collect({parse:false,stagehand:f.stagehand});assert.equal(result.ok,true);assert.equal(result.source,'dom:rendered-html');assert.equal(result.payload,null);assert.equal(f.calls,0);});
test('AliExpress accepts and unwraps validated Stagehand data',async()=>{const f=ali();const result=await f.collect();assert.equal(result.source,'stagehand:extract');assert.deepEqual(JSON.parse(JSON.stringify(result.payload)),product());assert.equal(result.payload.metadata,undefined);assert.equal(f.calls,1);});
for(const [label,response] of [['empty data',{data:{}}],['bare legacy object',product()],['null response',null],['empty title',{data:{...product(),title:' '}}],['wrong price type',{data:{...product(),price:12}}],['malformed specs',{data:{...product(),specs:{}}}],['nullable title',{data:{...product(),title:null}}]])test(`AliExpress ${label} retains raw-only outcome`,async()=>{const result=await ali({response}).collect();assert.equal(result.ok,true);assert.equal(result.source,'dom:rendered-html');assert.equal(result.payload,null);});
test('AliExpress extraction failure preserves raw capture without provider detail',async()=>{const result=await ali({error:true}).collect();assert.equal(result.ok,true);assert.equal(result.payload,null);assert.ok(!result.note.includes('SYNTHETIC_PRIVATE_PROVIDER_DETAIL'));});
test('missing Stagehand preserves raw capture',async()=>{const f=ali();const result=await f.collect({parse:true});assert.equal(result.payload,null);assert.equal(f.calls,0);});
test('unrendered page does not trigger extraction',async()=>{const f=ali({noTitle:true});assert.equal((await f.collect()).ok,false);assert.equal(f.calls,0);});
test('wait timeout still accepts a final rendered read',async()=>{assert.equal((await ali({waitError:true}).collect()).source,'stagehand:extract');});
test('actual artifact writer persists product data and raw HTML separately',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cookbook-r175-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const f=ali();const captured=await f.collect();const source=fs.readFileSync(new URL('fetchPdp.ts',root),'utf8');const start=source.indexOf('async function saveArtifacts('),end=source.indexOf('\n/** Persist the HTML',start);assert.ok(start>=0&&end>start);f.context.fs=fsp;f.context.path=path;f.context.OUT_DIR=dir;vm.runInContext(stripTypeScriptTypes(source.slice(start,end)),f.context);const out=await f.context.saveArtifacts('aliexpress','BR','synthetic',captured.payload,'<h1>Synthetic product</h1>');assert.deepEqual(JSON.parse(fs.readFileSync(out.payloadPath,'utf8')),product());assert.equal(fs.readFileSync(out.rawHtmlPath,'utf8'),'<h1>Synthetic product</h1>');});
function shopee(scripts=[],evaluateError=false){const context=load(process.env.COOKBOOK_R176_BASELINE||new URL('capture/shopee.ts',root));let listener;let detached=0;const page={on(event,fn){assert.equal(event,'response');listener=fn;},off(event,fn){assert.equal(fn,listener);detached++;},async evaluate(fn){if(evaluateError)throw Error('synthetic evaluation failure');return vm.runInNewContext(`(${fn.toString()})()`,{document:{querySelectorAll(){return scripts.map(textContent=>({textContent}));}}});}};const armed=vm.runInContext('shopeeAdapter',context).arm(page);return {collect:()=>armed.collect(page),response:body=>listener({url:()=> 'https://shopee.invalid/api/v4/pdp/get_pc',json:async()=>body}),get detached(){return detached}};}
for(const item of [{item_id:123},{itemid:'900719925474099312345'},{item_id:'00123',itemid:123}])test(`Shopee preserves valid SSR and XHR identity ${JSON.stringify(item)}`,async()=>{const payload={item,extra:'synthetic'};for(const source of ['ssr','xhr']){const f=shopee(source==='ssr'?[JSON.stringify({nested:payload})]:[]);if(source==='xhr')await f.response({data:payload});const result=await f.collect();assert.equal(result.ok,true);assert.deepEqual(JSON.parse(JSON.stringify(result.payload)),source==='ssr'?payload:{data:payload});assert.equal(f.detached,1);}});
for(const item of [{},{item_id:0},{item_id:-1},{item_id:1.5},{item_id:9007199254740992},{item_id:'0'},{item_id:' '},{item_id:'1e3'},{item_id:[]},{item_id:null},{item_id:1,itemid:2},{item_id:1,itemid:null},[]])test(`Shopee rejects invalid identity ${JSON.stringify(item)}`,async()=>{for(const source of ['ssr','xhr']){const f=shopee(source==='ssr'?[JSON.stringify({item})]:[]);if(source==='xhr')await f.response({data:{item}});assert.equal((await f.collect()).ok,false);assert.equal(f.detached,1);}});
test('Shopee searches later scripts after unrelated or malformed data',async()=>{const f=shopee(['{','{}','[]',JSON.stringify({nested:{item:{item_id:'123'}}})]);assert.equal((await f.collect()).ok,true);assert.equal(f.detached,1);});
test('empty SSR cannot mask blocked or empty classification',async()=>{const f=shopee(['{}']);const captured=await f.collect();assert.equal(captured.ok,false);const context=load(new URL('blockDetect.ts',root));const classify=vm.runInContext('classify',context);assert.equal(classify({navStatus:403,captureOk:captured.ok,bodyText:'',bodyBytes:3000}).outcome,'blocked');assert.equal(classify({navStatus:200,captureOk:captured.ok,bodyText:'Synthetic ordinary page',bodyBytes:3000}).outcome,'empty');});
test('Shopee detaches response listener when evaluation throws',async()=>{const f=shopee([],true);await assert.rejects(f.collect(),/synthetic evaluation failure/);assert.equal(f.detached,1);});
