import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import test from 'node:test';
const root=new URL('../src/',import.meta.url);
const CONFIG={maxRetries:2,computeUsdPerHour:0.6,proxyUsdPerGb:10,planConcurrency:2,extrapolateTo:100};
function source(file){return fs.readFileSync(file,'utf8').replace(/^import[\s\S]*?from\s+["'][^"']+["'];\s*/gm,'').replace(/^export /gm,'');}
function context(extra={}){return vm.createContext({CONFIG,...extra});}
function evaluate(code,ctx){vm.runInContext(stripTypeScriptTypes(code),ctx);return ctx;}
const metrics=evaluate(source(process.env.COOKBOOK_R178_METRICS_BASELINE||new URL('metrics.ts',root)),context());
const rec=(overrides={})=>({url:'https://example.com/product',competitor:'shopee',country:'BR',outcome:'ok',reason:'synthetic',source:'synthetic',durationMs:1000,bytes:100,captchaEncountered:1,captchaSolved:0,sessionId:'synthetic-session',liveViewUrl:'https://example.com/replay',attempts:1,...overrides});
async function retry(outcomes=['blocked','empty','ok']){let calls=0,persisted,now=0;const records=[];const ctx=context({Date:{now:()=>now},fetchOnce:async(input,index)=>{assert.equal(index,calls);const value=rec({outcome:outcomes[calls],sessionId:`synthetic-${calls}`});records.push(value);calls++;now+=1500;return value;},appendManifest:async value=>{persisted=value;}});const text=source(process.env.COOKBOOK_R178_BASELINE||new URL('fetchPdp.ts',root));const start=text.indexOf('async function fetchPdp('),end=text.indexOf('// ─────',start);evaluate(text.slice(start,end),ctx);const result=await ctx.fetchPdp({});return {result,persisted,calls,records};}
test('retry loop retains and persists all attempt telemetry',async()=>{const {result,persisted,calls,records}=await retry();assert.equal(calls,3);assert.equal(result.durationMs,3000);assert.equal(result.elapsedMs,4500);assert.equal(result.bytes,300);assert.equal(result.captchaEncountered,3);assert.equal(result.attemptHistory.length,3);assert.equal(result.attemptHistory[0].outcome,'blocked');assert.equal(result.attemptHistory[1].outcome,'empty');assert.equal(result.firstAttemptOutcome,'blocked');assert.equal(result.sessionId,'synthetic-2');assert.equal(persisted,result);assert.equal(records[2].durationMs,1000);});
test('successful first attempt does not retry',async()=>{const {result,calls}=await retry(['ok']);assert.equal(calls,1);assert.equal(result.attempts,1);assert.equal(result.firstAttemptOutcome,'ok');});
test('exhausted retries retain all work and final failure',async()=>{const {result,calls}=await retry(['blocked','blocked','blocked']);assert.equal(calls,3);assert.equal(result.outcome,'blocked');assert.equal(result.bytes,300);});
test('cost applies minimums to every allocated attempt',async()=>{const {result}=await retry();const single=metrics.recordCostUsd(rec());assert.ok(Math.abs(metrics.recordCostUsd(result)-single*3)<1e-10);});
test('cost rounds each attempt independently',()=>{const a=rec({durationMs:61000,elapsedMs:61000,bytes:1000001});const b=rec({durationMs:1,elapsedMs:1,bytes:1});const value=rec({attempts:2,attemptHistory:[a,b]});assert.ok(Math.abs(metrics.recordCostUsd(value)-0.06)<1e-10);});
test('aggregation separates stage wall, URL latency, work and bytes denominators',async()=>{const {result}=await retry();const m=metrics.aggregate([result],1,6000);assert.equal(m.avgLatencyMs,4500);assert.equal(m.wallClockMs,6000);assert.equal(m.totalAttemptDurationMs,3000);assert.equal(m.totalAttempts,3);assert.equal(m.totalBytes,300);assert.equal(m.avgBytesPerAttempt,100);assert.equal(m.avgBytesPerUrl,300);assert.equal(m.captchaEncountered,3);assert.equal(m.firstPassRate,0);assert.equal(m.successRate,1);});
test('extrapolation scales whole URLs and reports expected successes',async()=>{const {result}=await retry();const m=metrics.aggregate([result,rec({outcome:'blocked',elapsedMs:1500})],2,5000);const e=metrics.extrapolate(m,100);assert.equal(e.estWallClockMin,2.5);assert.equal(e.estProxyGb,20000/1e9);assert.equal(e.expectedSuccessfulUrls,50);assert.equal(e.perUrlCostUsd,m.estCostUsd/2);assert.equal(e.estCostUsd,m.estCostUsd*50);});
test('historical retries with missing observations cannot produce estimates',()=>{const old=rec({attempts:3});assert.throws(()=>metrics.recordCostUsd(old),/Incomplete retry telemetry/);assert.throws(()=>metrics.aggregate([old],1,1000),/Incomplete retry telemetry/);assert.throws(()=>metrics.buildMatrix([old]),/Incomplete retry telemetry/);});
test('historical single attempt remains measurable',()=>{assert.equal(metrics.aggregate([rec()],1,1000).avgLatencyMs,1000);});
test('missing session identity yields unknown cost through extrapolation',()=>{const m=metrics.aggregate([rec({sessionId:''})],1,1000);assert.equal(m.estCostUsd,null);assert.equal(metrics.extrapolate(m).estCostUsd,null);});
for(const overrides of [{attempts:2,attemptHistory:[]},{durationMs:NaN},{bytes:-1},{elapsedMs:Infinity}])test(`rejects invalid telemetry ${JSON.stringify(overrides)}`,()=>{assert.throws(()=>metrics.aggregate([rec(overrides)],1,1000));});
test('matrix throughput uses mean URL latency, not median',()=>{const records=[rec({elapsedMs:1000}),rec({elapsedMs:1000}),rec({elapsedMs:10000,outcome:'blocked'})];const [cell]=metrics.buildMatrix(records);assert.equal(cell.p50LatencyMs,1000);assert.equal(cell.estDailyCapacity,43200);assert.equal(cell.estDailySuccessfulUrls,28800);});
test('manifest serializes cumulative and per-attempt telemetry',async()=>{const {result}=await retry();let row;const ctx=context({Date,OUT_DIR:'/synthetic',path:{join:(...x)=>x.join('/'),relative:(_,x)=>x},fs:{mkdir:async()=>{},appendFile:async(_,text)=>{row=JSON.parse(text);}}});const text=source(new URL('fetchPdp.ts',root));const start=text.indexOf('async function appendManifest('),end=text.indexOf('/** True if',start);evaluate(text.slice(start,end),ctx);await ctx.appendManifest(result);assert.equal(row.attemptHistory.length,3);assert.equal(row.durationMs,3000);assert.equal(row.elapsedMs,4500);assert.equal(row.captchaEncountered,3);assert.equal(row.bytes,300);});
test('report labels disclose attempt, URL, success and unknown-cost scopes',async()=>{const {result}=await retry();const lines=[];const ctx=evaluate(source(new URL('report.ts',root)),context({console:{log:line=>lines.push(line)}}));ctx.printStageSummary(metrics.aggregate([result],1,6000));ctx.printExtrapolation(metrics.extrapolate(metrics.aggregate([rec({sessionId:''})],1,1000)));ctx.printMatrix(metrics.buildMatrix([result]));const text=lines.join('\n');for(const label of ['URL elapsed','summed attempt work','/attempt','/URL','unknown','expected successful','mean URL elapsed'])assert.ok(text.includes(label),label);});
test('failed attempt retains already observed traffic and CAPTCHA events',async()=>{let closed=0;const ctx=context({Date,clearTimeout:()=>{},setTimeout:()=>0,adapterFor:()=>({competitor:'shopee'}),createSession:async()=>({pwPage:{},sessionId:'synthetic-session',liveViewUrl:'https://example.com',close:async()=>{closed++;}}),attachCaptchaTelemetry:()=>({encountered:2,solved:1}),attachByteCounter:async()=>({bytes:()=>345}),blockHeavyAssets:async()=>{throw Error('synthetic failure');}});const text=source(new URL('fetchPdp.ts',root));const start=text.indexOf('async function fetchOnce('),end=text.indexOf('/** Fetch a URL',start);evaluate(text.slice(start,end),ctx);const result=await ctx.fetchOnce({url:'https://example.com',competitor:'shopee',country:'BR',id:'synthetic'},0);assert.equal(result.outcome,'blocked');assert.equal(result.bytes,345);assert.equal(result.captchaEncountered,2);assert.equal(result.captchaSolved,1);assert.equal(closed,1);});
test('progress output labels cumulative work and elapsed time',async()=>{const {result}=await retry();const lines=[];const ctx=context({console:{log:x=>lines.push(x)}});const text=source(new URL('stagedRun.ts',root));const start=text.indexOf('function onRecord('),end=text.indexOf('// ─────',start);evaluate(text.slice(start,end),ctx);ctx.onRecord(result,1,1);assert.ok(lines[0].includes('URL 4.5s; work 3.0s; observed'));});
