import { StagehandCreateOptionsSchema } from "@browserbasehq/stagehand";
/**
 * Job Runner — executes portal automation steps using Stagehand + Browserbase.
 *
 * This is the core engine that takes a PortalDefinition (generated by Claude Code)
 * and executes each step deterministically using Stagehand AI.
 *
 * The key self-healing property: steps are natural-language instructions,
 * so Stagehand adapts when the portal UI changes.
 */

import Browserbase from "@browserbasehq/sdk";
import { Stagehand, browserbase, localBrowser } from "@browserbasehq/stagehand";
import { z } from "zod";
import {
  claimJob,
  portalSupportsPaymentInstrument,
  replaceTemplateVars,
  requireSuccessfulStepAction,
  validateJobData,
} from "./job-contracts.mjs";
import type {
  CreateJobRequest,
  JobResponse,
  JobStatus,
  PortalDefinition,
  AutomationStep,
  JobData,
} from "./types.js";

// ---------------------------------------------------------------------------
// In-memory job store
// ---------------------------------------------------------------------------

interface JobState {
  request: CreateJobRequest;
  portal: PortalDefinition;
  status: JobStatus;
  sessionId?: string;
  jobData?: JobData;
  errorMessage?: string;
  // MFA support
  mfaResolver?: (code: string) => void;
  mfaTimer?: ReturnType<typeof setTimeout>;
  mfaCode?: string;
  stagehand?: Stagehand;
  page?: any;
}

const jobs = new Map<string, JobState>();

const bb = new Browserbase({ apiKey: process.env.BROWSERBASE_API_KEY! });

// ---------------------------------------------------------------------------
// Public API (used by server.ts)
// ---------------------------------------------------------------------------

export async function createJob(
  request: CreateJobRequest,
  portal: PortalDefinition,
): Promise<JobResponse> {
  const candidate: JobState = {
    request,
    portal,
    status: "pending",
  };
  const { state, created } = claimJob(jobs, candidate);
  if (!created) return toResponse(state);

  // Run the job in the background
  runJob(state).catch((err) => {
    console.error(`Job ${request.job_id} fatal error:`, err);
    state.status = "failure";
    state.errorMessage = err instanceof Error ? err.message : String(err);
  });

  return toResponse(state);
}

export function getJob(jobId: string): JobResponse | null {
  const state = jobs.get(jobId);
  if (!state) return null;
  return toResponse(state);
}

export async function submitMfa(
  jobId: string,
  mfaCode: string,
): Promise<JobResponse | null> {
  const state = jobs.get(jobId);
  if (!state) return null;

  if (state.status !== "mfa_requested" || !state.mfaResolver) {
    return toResponse(state);
  }

  // Resume execution with the MFA code
  state.mfaResolver(mfaCode);
  if (state.mfaTimer) clearTimeout(state.mfaTimer);
  state.mfaTimer = undefined;
  state.mfaResolver = undefined;
  state.status = "in_progress";

  return toResponse(state);
}

// ---------------------------------------------------------------------------
// Job execution engine
// ---------------------------------------------------------------------------

async function runJob(state: JobState): Promise<void> {
  state.status = "in_progress";
  const { request, portal } = state;
  const steps =
    request.type === "bill_pull"
      ? portal.billPullSteps
      : (portal.billPaySteps ?? []);

  if (steps.length === 0) {
    state.status = "failure";
    state.errorMessage = `No ${request.type} steps defined for portal ${portal.name}`;
    return;
  }

  if (!portalSupportsPaymentInstrument(request, portal)) {
    state.status = "failure";
    state.errorMessage =
      `Portal ${portal.name} does not support selecting the requested payment instrument`;
    return;
  }

  let session: Awaited<ReturnType<typeof bb.sessions.create>> | undefined;
  let stagehand: Stagehand | undefined;
  try {
    session = await bb.sessions.create({
      keepAlive: true,
      browserSettings: {
        solveCaptchas: true,
        viewport: { width: 1280, height: 900 },
      },
    });
    state.sessionId = session.id;
    console.log(
      `[${request.job_id}] Browserbase session: https://www.browserbase.com/sessions/${session.id}`,
    );

    stagehand = await Stagehand.create(
      StagehandCreateOptionsSchema.parse({
        browser: await localBrowser.connect({ cdpUrl: session.connectUrl }),
        model: {
          modelName: "anthropic/claude-haiku-4-5-20251001",
          apiKey: process.env.ANTHROPIC_API_KEY,
        },
      }),
    );
    const page = await stagehand.browser.context.activePage();
    if (!page) throw new Error("Stagehand did not create an active page");
    state.stagehand = stagehand;
    state.page = page;

    for (let i = 0; i < steps.length; i++) {
      const step = steps[i];
      console.log(
        `[${request.job_id}] Step ${i + 1}/${steps.length}: ${step.description}`,
      );

      const result = await executeStep(stagehand, page, step, request, state);

      // Check for MFA after steps that might trigger it
      if (step.action === "observe" && portal.mfaDetection) {
        const isMfa = detectMfa(result, portal.mfaDetection.indicators);
        if (isMfa) {
          console.log(`[${request.job_id}] MFA detected — pausing for code`);
          state.status = "mfa_requested";

          // Wait for MFA code to be provided via PATCH /job/:id
          const mfaCode = await waitForMfa(state);
          console.log(`[${request.job_id}] MFA code received — resuming`);

          // Replace {{mfa_code}} in subsequent steps
          state.mfaCode = mfaCode;
          state.status = "in_progress";
        }
      }

      // Capture final result
      if (step.isFinalResult && result) {
        state.jobData = validateJobData(request, result);
      }
    }

    state.status = state.jobData ? "success" : "failure";
    if (!state.jobData) {
      state.errorMessage =
        "No data extracted — final extract step may have failed";
    }
  } catch (err) {
    console.error(`[${request.job_id}] Error:`, err);
    state.status = "failure";
    state.errorMessage = err instanceof Error ? err.message : String(err);
  } finally {
    // Release the session
    try {
      await stagehand?.close();
      await stagehand?.browser.close();
    } catch {}
    try {
      if (session) await bb.sessions.update(session.id, {
        status: "REQUEST_RELEASE",
      });
    } catch {}
  }
}

// ---------------------------------------------------------------------------
// Step executor
// ---------------------------------------------------------------------------

async function executeStep(
  stagehand: Stagehand,
  page: any,
  step: AutomationStep,
  request: CreateJobRequest,
  state: JobState,
): Promise<any> {
  const instruction = replaceTemplateVars(
    step.instruction ?? "",
    request,
    state.mfaCode,
  );

  switch (step.action) {
    case "navigate":
      await page.goto(instruction, {
        waitUntil: "domcontentloaded",
        timeout: 60000,
      });
      return null;

    case "act":
      {
        const action = await stagehand.act(instruction, { page: page });
        requireSuccessfulStepAction(action, step.description);
      }
      return null;

    case "extract": {
      const extractOpts: any = { instruction };
      if (step.schema) {
        const zodFields: Record<string, any> = {};
        for (const [key, type] of Object.entries(step.schema)) {
          if (type === "string") zodFields[key] = z.string();
          else if (type === "number") zodFields[key] = z.number();
          else if (type === "boolean") zodFields[key] = z.boolean();
        }
        if (Object.keys(zodFields).length > 0) {
          extractOpts.schema = z.object(zodFields);
        }
      }
      return (
        await stagehand.extract(
          instruction,
          extractOpts.schema ?? z.object({ text: z.string() }),
          { page },
        )
      ).data;
    }

    case "observe": {
      const observations = (
        await stagehand.observe(instruction, { page: page })
      ).data;
      return observations;
    }

    case "screenshot": {
      await page.screenshot({ fullPage: false });
      return null;
    }

    case "wait":
      await new Promise((resolve) => setTimeout(resolve, step.waitMs ?? 2000));
      return null;

    default:
      console.warn(`Unknown step action: ${step.action}`);
      return null;
  }
}

// ---------------------------------------------------------------------------
// MFA detection & wait
// ---------------------------------------------------------------------------

function detectMfa(observeResult: any, indicators: string[]): boolean {
  if (!observeResult) return false;

  const text = JSON.stringify(observeResult).toLowerCase();
  return indicators.some((indicator) => text.includes(indicator.toLowerCase()));
}

function waitForMfa(state: JobState): Promise<string> {
  return new Promise((resolve, reject) => {
    state.mfaResolver = resolve;
    state.mfaTimer = setTimeout(() => {
      state.mfaResolver = undefined;
      state.mfaTimer = undefined;
      reject(new Error("Timed out waiting for MFA code after 5 minutes"));
    }, 300_000);
  });
}

// ---------------------------------------------------------------------------
// Response builder
// ---------------------------------------------------------------------------

function toResponse(state: JobState): JobResponse {
  return {
    job_id: state.request.job_id,
    status: state.status,
    type: state.request.type,
    job_data: state.jobData,
    error_message: state.errorMessage,
    session_id: state.sessionId,
  };
}
