#!/usr/bin/env python3
"""Import pinned source trees while retaining provenance and package boundaries."""

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys

SOURCES = (
    ("templates", "examples", "public"),
    ("playbook", "playbook", "public"),
    ("integrations", "integrations", "public"),
    ("private_workflows", "use-cases", "private"),
)
ADMIN = {".github", ".husky", ".claude", ".codex", ".changeset"}
CACHES = {"__pycache__", "node_modules", ".next", ".venv", "venv", ".cache", ".pytest_cache", ".DS_Store"}
ARTIFACTS = {"downloads", "downloaded_files", "browser_downloads"}
SECRET_NAME = re.compile(r"(?:KEY|TOKEN|SECRET|PASSWORD)", re.I)
ASSIGNMENT = re.compile(r"^(\s*(?:export\s+)?)([A-Za-z_][A-Za-z_0-9]*)(\s*=).*$")
TOKEN = re.compile(
    r"(?<![A-Za-z0-9_-])(?:"
    r"sk-(?:proj-|ant-)?[A-Za-z0-9_-]{32,}|"
    r"bb_live_[A-Za-z0-9]{20,}|"
    r"gh[pousr]_[A-Za-z0-9]{30,}|"
    r"github_pat_[A-Za-z0-9_]{40,}|"
    r"xox[baprs]-[A-Za-z0-9-]{20,}|"
    r"AKIA[A-Z0-9]{16}"
    r")(?![A-Za-z0-9_-])"
)


def git(root, *args):
    return subprocess.check_output(["git", "-C", str(root), *args])


def digest(data):
    return hashlib.sha256(data).hexdigest()


def env_template(path):
    name = path.name.lower()
    return "env" in name and (name.endswith((".example", ".sample")) or name.startswith((".example.env", ".sample.env")))


def exclusion(path, source):
    parts = path.parts
    if source == "playbook" and (path.as_posix().startswith("node/playwright/_tools/download/files/") or path.as_posix() == "guides/1password/1pass_new.zip"):
        return "Generated browser download or packaged local extension archive"
    if source == "private_workflows":
        if path.suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".pdf"} and not any(token in path.name.lower() for token in ("logo", "stagehand", "browsegpt", "workflow_diagram", "architecture-pipeline", "bb.jpeg")):
            return "Captured screenshot or customer document excluded from consolidated source"
        if path.suffix.lower() == ".csv" and path.name != "mcc_codes.csv":
            return "Customer dataset or captured CSV output; provide a local fixture before running"
        if path.name == "results.json" or path.suffix.lower() == ".log":
            return "Captured runtime output"
        if path.name.lower() in {"storage-state.json", "storagestate.json", "cookies.json", "auth.json"}:
            return "Persisted authentication or browser state"
    if any(part in ADMIN for part in parts):
        return "Source repository automation and agent configuration"
    if path.suffix == ".tsbuildinfo":
        return "Generated TypeScript incremental compiler state"
    if any(part in CACHES for part in parts) or path.suffix in {".pyc", ".pyo"}:
        return "Dependency cache or generated bytecode"
    if any(part.lower() in ARTIFACTS for part in parts):
        return "Downloaded runtime artifact"
    if path.name in {".env", ".env.local", ".env.production", ".env.development"}:
        return "Local environment configuration"
    return None


def sanitize(data):
    text = data.decode("utf-8")
    lines = []
    for line in text.splitlines(keepends=True):
        ending = "\r\n" if line.endswith("\r\n") else "\n" if line.endswith("\n") else ""
        match = ASSIGNMENT.match(line.rstrip("\r\n"))
        if match and SECRET_NAME.search(match[2]):
            line = "".join(match.groups()) + ending
        lines.append(line)
    return "".join(lines).encode()


def adapt_source(source, path, data):
    if source != "templates" or path.as_posix() != "typescript/getting-started-with-browserbase/index.ts":
        return data, None
    expected = b'  const response = await bb.fetchAPI.create({ url: targetUrl, allowRedirects: true });\n'
    replacement = expected + b'  if (typeof response.content !== "string") {\n    throw new Error("Expected HTML text from the Browserbase Fetch API.");\n  }\n'
    if data.count(expected) != 1:
        raise ValueError("TypeScript getting-started Fetch boundary changed; review the import adaptation")
    return data.replace(expected, replacement), "Validate Fetch response content before treating it as HTML text"


def dependency_escapes(destination, planned):
    errors = []
    available = set(planned)
    for relative, (data, _) in planned.items():
        path = Path(relative)
        if path.name != "package.json":
            continue
        try:
            package = json.loads(data)
        except (UnicodeDecodeError, json.JSONDecodeError):
            errors.append(relative)
            continue
        for field in ("dependencies", "devDependencies", "optionalDependencies"):
            for value in package.get(field, {}).values():
                if not isinstance(value, str) or not value.startswith(("file:", "link:")):
                    continue
                target = (destination / path.parent / value.split(":", 1)[1]).resolve()
                try:
                    target_relative = target.relative_to(destination.resolve()).as_posix()
                except ValueError:
                    errors.append(relative)
                    continue
                if target_relative not in available and not any(p.startswith(target_relative.rstrip("/") + "/") for p in available):
                    errors.append(relative)
    return sorted(set(errors))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=Path("/tmp/browserbase-cookbook-sources"))
    parser.add_argument("--destination", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--scope", choices=("public", "private", "all"), default="public",
                        help="Source boundary to refresh (default: public)")
    parser.add_argument("--refresh", action="store_true",
                        help="Update unchanged imported files to the selected upstream revisions")
    parser.add_argument("--replace-adaptations", action="store_true",
                        help="With --refresh, explicitly permit replacement of recorded downstream adaptations")
    args = parser.parse_args()
    if args.replace_adaptations and not args.refresh:
        parser.error("--replace-adaptations requires --refresh")
    destination = args.destination.resolve()
    previous_manifest = None
    previous_path = destination / "SOURCE_MANIFEST.json"
    if previous_path.is_file():
        previous_manifest = json.loads(previous_path.read_text())
    selected = [source for source in SOURCES if args.scope == "all" or source[2] == args.scope]
    selected_repositories = {f"https://github.com/browserbase/{name}" for name, _, _ in selected}
    retained_sources = [] if not previous_manifest else [
        source for source in previous_manifest.get("sources", [])
        if source.get("repository") not in selected_repositories
    ]
    manifest = {"schema_version": 1, "sources": retained_sources}
    planned = {}
    findings = []
    for name, target_root, visibility in selected:
        root = args.source_dir / name
        commit = git(root, "rev-parse", "HEAD").decode().strip()
        source = {"repository": f"https://github.com/browserbase/{name}", "commit": commit,
                  "visibility": visibility, "destination": target_root, "files": []}
        tracked = git(root, "ls-tree", "-rz", "--full-tree", commit).split(b"\0")
        objects = [item.split(b"\t", 1)[0].split()[2] for item in tracked if item and item.split(b"\t", 1)[0].split()[1] == b"blob"]
        batch = subprocess.run(["git", "-C", str(root), "cat-file", "--batch"], input=b"\n".join(objects) + b"\n", capture_output=True, check=True).stdout
        blobs = {}
        offset = 0
        for object_id in objects:
            end = batch.index(b"\n", offset)
            size = int(batch[offset:end].rsplit(b" ", 1)[1])
            blobs[object_id.decode()] = batch[end + 1:end + 1 + size]
            offset = end + size + 2
        for item in sorted(filter(None, tracked)):
            metadata, raw_path = item.split(b"\t", 1)
            mode, kind, object_id = metadata.decode().split()
            original = raw_path.decode()
            path = PurePosixPath(original)
            if path.is_absolute() or ".." in path.parts:
                raise ValueError(f"Unsafe source path in {name}")
            relative = f"{target_root}/" + ("UPSTREAM_README.md" if original == "README.md" else original)
            data = blobs[object_id] if kind == "blob" else b""
            original_hash = digest(data)
            reason = exclusion(path, name)
            if kind != "blob" or mode == "120000":
                reason = "External gitlink or symbolic link requires explicit migration"
            record = {"source_path": original, "path": relative, "sha256": original_hash,
                      "source_sha256": original_hash, "action": "imported"}
            if reason:
                record.update(action="excluded", reason=reason)
            else:
                if env_template(path):
                    data = sanitize(data)
                data, adaptation = adapt_source(name, path, data)
                if TOKEN.search(data.decode("utf-8", errors="replace")):
                    findings.append(relative)
                record["sha256"] = digest(data)
                if record["sha256"] != original_hash:
                    record.update(action="transformed", reason=adaptation or "Blank secret-like environment template assignments")
                if original == "README.md":
                    record.update(action="transformed", reason="Preserve source overview as UPSTREAM_README.md" + ("; sanitize template" if record["sha256"] != original_hash else ""))
                planned[relative] = (data, int(mode, 8) & 0o777)
            source["files"].append(record)
        manifest["sources"].append(source)
    if findings:
        print("Potential credential tokens require review in these paths:", file=sys.stderr)
        print("\n".join(sorted(findings)), file=sys.stderr)
        return 2
    escapes = dependency_escapes(destination, planned)
    if escapes:
        print("Unresolved local package dependencies in these paths:", file=sys.stderr)
        print("\n".join(escapes), file=sys.stderr)
        return 2
    planned["SOURCE_MANIFEST.json"] = ((json.dumps(manifest, indent=2) + "\n").encode(), 0o644)
    previous_files = {
        item.get("path"): item
        for source in (previous_manifest or {}).get("sources", [])
        for item in source.get("files", [])
    }
    conflicts = []
    for relative, (data, _) in planned.items():
        target = destination / relative
        if not target.resolve().is_relative_to(destination):
            raise ValueError(f"Destination escapes workspace: {relative}")
        if not target.exists() or (target.is_file() and not target.is_symlink() and target.read_bytes() == data):
            continue
        if target.is_symlink() or not target.is_file() or not args.refresh:
            conflicts.append(relative)
            continue
        if relative == "SOURCE_MANIFEST.json":
            continue
        previous = previous_files.get(relative)
        if previous is None or previous.get("action") == "excluded":
            conflicts.append(relative)
            continue
        expected = previous.get("adaptation", {}).get("sha256", previous.get("sha256"))
        if digest(target.read_bytes()) != expected or ("adaptation" in previous and not args.replace_adaptations):
            conflicts.append(relative)
    if conflicts:
        print("Refusing local changes or recorded adaptations; review the diff first. "
              "Use --refresh for unchanged imports and add --replace-adaptations only to retire reviewed patches:", file=sys.stderr)
        print("\n".join(conflicts), file=sys.stderr)
        return 2
    written = 0
    for relative, (data, mode) in planned.items():
        target = destination / relative
        if target.exists() and target.read_bytes() == data:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        target.chmod(mode)
        written += 1
    excluded = sum(f["action"] == "excluded" for s in manifest["sources"] for f in s["files"])
    print(f"Imported {len(planned) - 1} files across {len(selected)} selected sources; {excluded} exclusions; {written} files written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
