import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import test from 'node:test';
const root=new URL('../',import.meta.url);
const raw=fs.readFileSync(process.env.COOKBOOK_R182_PRODUCTS_BASELINE||new URL('shared/extract.ts',root),'utf8');
const start=raw.indexOf('export const EXTRACT_PRODUCTS =');const end=raw.indexOf('/** unavailabilities',start);const scope=vm.createContext({});vm.runInContext(stripTypeScriptTypes(raw.slice(start,end<0?undefined:end).replace('export const','globalThis.')),scope);const expression=scope.EXTRACT_PRODUCTS;
const item={id:'synthetic-item',item_data:{name:'Synthetic product',product_type:'REGULAR',category_id:'synthetic-category',variations:[{item_variation_data:{name:'Synthetic size',price_money:{amount:123},sku:'synthetic-sku'}}]}};
function extraction(plan={}){const calls=[];const counts={};const fetch=async url=>{const type=new URL(url).searchParams.get('types');const index=counts[type]??0;counts[type]=index+1;calls.push({type,url});const response=typeof plan[type]==='function'?plan[type](index):plan[type]?.[index]??{body:{objects:[]}};if(response.throw)throw Error('PRIVATE_TRANSPORT_DETAIL');return {ok:response.status===undefined||response.status===200,status:response.status??200,json:async()=>{if(response.jsonError)throw Error('PRIVATE_JSON_DETAIL');return response.body;}};};return {calls,run:()=>vm.runInNewContext(expression,{fetch})};}
test('complete successful empty enumeration is explicitly complete',async()=>{const f=extraction();const result=await f.run();assert.equal(result.complete,true);assert.equal(result.rows.length,0);assert.deepEqual(f.calls.map(c=>c.type),['ITEM','CATEGORY']);});
test('multi-page products and categories produce mapped rows after both finish',async()=>{const f=extraction({ITEM:[{body:{objects:[],cursor:'second'}},{body:{objects:[item]}}],CATEGORY:[{body:{objects:[{id:'synthetic-category',category_data:{name:'Synthetic category'}}]}}]});const result=await f.run();assert.equal(result.complete,true);assert.equal(result.rows[0].name,'Synthetic product');assert.equal(result.rows[0].price,'1.23');assert.equal(result.rows[0].category,'Synthetic category');assert.ok(f.calls[1].url.includes('cursor=second'));});
for(const [name,response] of [['HTTP401',{status:401,body:{errors:[]}}],['transport',{throw:true}],['JSON',{jsonError:true}],['missing objects',{body:{}}],['array body',{body:[]}],['null body',{body:null}],['errors with HTTP200',{body:{objects:[],errors:[{code:'synthetic'}]}}],['malformed objects',{body:{objects:{}}}],['missing data',{body:{objects:[{id:'synthetic'}]}}],['invalid item',{body:{objects:[{id:'synthetic',item_data:{name:'Synthetic',product_type:'REGULAR'}}]}}],['invalid variation',{body:{objects:[{id:'synthetic',item_data:{name:'Synthetic',product_type:'REGULAR',variations:[null]}}]}}],['cursor shape',{body:{objects:[],cursor:123}}]])test(`${name} cannot become a successful empty export`,async()=>{await assert.rejects(extraction({ITEM:[response]}).run(),error=>!error.message.includes('PRIVATE'));});
test('failed later page cannot return partial rows',async()=>{await assert.rejects(extraction({ITEM:[{body:{objects:[item],cursor:'second'}},{status:500,body:{}}]}).run(),/HTTP 500/);});
test('failed category source prevents otherwise valid product output',async()=>{await assert.rejects(extraction({ITEM:[{body:{objects:[item]}}],CATEGORY:[{status:403,body:{}}]}).run(),/HTTP 403/);});
test('repeated cursor fails instead of looping or claiming completion',async()=>{await assert.rejects(extraction({ITEM:()=>({body:{objects:[],cursor:'same'}})}).run(),/Repeated catalog cursor/);});
test('page limit fails explicitly instead of truncating',async()=>{const f=extraction({ITEM:index=>({body:{objects:[],cursor:String(index)}})});await assert.rejects(f.run(),/page limit/);assert.equal(f.calls.length,1000);});
async function caller(result){let handler,delivered=0,closed=0;const context=vm.createContext({defineFn:(_,fn)=>handler=fn,workflowParams:{},EXTRACT_PRODUCTS:expression,openPlatformASession:async()=>({page:{evaluate:async()=>result},sessionId:'synthetic',close:async()=>{closed++;}}),productsCsv:()=> 'synthetic,csv',deliverCsv:async()=>{delivered++;return 100;},ok:value=>({ok:true,...value}),fail:()=>({ok:false})});const source=fs.readFileSync(new URL('functions/products.ts',root),'utf8').replace(/^import .*;\n/gm,'');vm.runInContext(stripTypeScriptTypes(source),context);return {result:await handler({}),delivered,closed};}
test('handler rejects legacy empty results without completion evidence',async()=>{const actual=await caller({rows:[]});assert.equal(actual.result.ok,false);assert.equal(actual.delivered,0);assert.equal(actual.closed,1);});
test('handler delivers a verified empty enumeration',async()=>{const actual=await caller(await extraction().run());assert.equal(actual.result.ok,true);assert.equal(actual.delivered,1);assert.equal(actual.closed,1);});
